//! Choosing a skeleton and placing it on the imported mesh.
//!
//! # Boundary
//!
//! This is projection, not algorithm (`memory/architecture.md` §2). The fitting
//! lives in `m2m_rig::fit`; what happens here is turning a `glb::Document` into
//! the plain inputs that crate takes. `m2m-rig` deliberately does **not** depend
//! on `m2m-io` — the rigging maths has no business knowing about file formats —
//! so somebody has to bridge the two, and the adapter is the right somebody.

use m2m_rig::fit::{Fitted, RestPose};
use serde::{Deserialize, Serialize};

// Generated by `build.rs`: every rig `.glb`, by file name.
include!(concat!(env!("OUT_DIR"), "/skeletons.rs"));

/// A creature template offered in the Choose Skeleton step.
#[derive(Debug, Serialize)]
pub struct SkeletonTemplate {
    /// The template's name, e.g. `human`.
    pub name: String,
    /// How many bones its skeleton has.
    pub bones: usize,
    /// Chain names, so the UI can say what the rig actually covers.
    pub chains: Vec<String>,
    /// Whether the rig for it is available to fit.
    ///
    /// A manifest naming a `.glb` that is not embedded would otherwise fail
    /// only when the user picked it.
    pub available: bool,
    /// A creature-specific tip for placing this skeleton (design.md §7).
    pub guidance: String,
}

/// A template skeleton placed on a mesh, ready to draw.
///
/// Deserialisable as well as serialisable: it goes out to the frontend to be
/// drawn and comes back to be bound, which is what will let a user's manual
/// adjustments reach the solver once the gizmo exists.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct FittedSkeleton {
    /// Bone names.
    pub bones: Vec<String>,
    /// Each bone's parent, as an index into `bones`. `None` for a root.
    ///
    /// Carried because a skeleton is drawn as segments between a bone and its
    /// parent, and [`Fitted`] is only names and positions — the hierarchy lives
    /// in the rig file's node graph.
    pub parents: Vec<Option<usize>>,
    /// World-space position of each bone, in metres.
    pub positions: Vec<[f32; 3]>,
    /// Each bone's **local rest rotation**, xyzw, taken from the template.
    ///
    /// Fitting moves joints; it does not turn them, so these come through from
    /// the rig the template names rather than from the fit. Measured: all 66
    /// bones of `rig-human.glb` carry one, up to 179.94 degrees. Dropping them
    /// costs bone roll — which artists notice — and puts every clip authored
    /// against the template out of alignment, because the clip's rest pose and
    /// the exported rig's would no longer agree.
    pub rotations: Vec<[f32; 4]>,
    /// The uniform scale the template was fitted with, reported so a wildly
    /// wrong pick is visible as a number and not only as a shape.
    pub scale: f32,
    /// The arm pose detected from where the arms landed — `"t-pose"`,
    /// `"a-pose"`, `"arms-down"` or `"other"`. `"other"` for a non-human
    /// template, whose arms these bone names do not describe. The UI reports it
    /// rather than the app silently assuming a pose (P3-P2).
    pub pose: String,
}

/// Errors the skeleton step can produce.
#[derive(Debug, thiserror::Error)]
pub enum RigError {
    /// The shipped manifests did not parse.
    #[error("template manifests: {0}")]
    Manifests(#[from] serde_json::Error),
    /// No template by that name ships.
    #[error("no template named {0}")]
    UnknownTemplate(String),
    /// The template names a rig file that is not embedded.
    #[error("template {template} needs {skeleton}, which is not bundled")]
    MissingSkeleton {
        /// The template that asked.
        template: String,
        /// The file it named.
        skeleton: String,
    },
    /// A rig file could not be read.
    #[error(transparent)]
    Read(#[from] m2m_io::glb::GlbError),
    /// The model the user imported could not be read.
    #[error(transparent)]
    Import(#[from] m2m_io::import::ImportError),
    /// The rig carries no skin, so there is no joint list to fit.
    #[error("{0} has no skin, so it names no bones")]
    NoSkin(String),
    /// There was nothing to bind, or nothing to bind it to.
    #[error("cannot bind: {reason}")]
    NothingToBind {
        /// What was missing.
        reason: &'static str,
    },
    /// A bone's parent appears after it, which `fbx::build` cannot express.
    #[error("bone {bone} has parent {parent}, which comes after it")]
    BadBoneOrder {
        /// The bone whose parent is out of order.
        bone: usize,
        /// The parent that comes too late.
        parent: usize,
    },
    /// Writing the FBX failed.
    #[error(transparent)]
    Fbx(#[from] m2m_io::fbx::FbxError),
    /// The library has no clip by that name.
    #[error("no clip named {0}")]
    UnknownClip(String),
    /// The fitting pipeline could not place the skeleton.
    #[error("cannot fit {template}: the mesh or the template has nothing to work with")]
    CannotFit {
        /// The template that was being fitted.
        template: String,
    },
}

/// Every template that ships, with whether its rig is actually bundled.
pub fn templates() -> Result<Vec<SkeletonTemplate>, RigError> {
    Ok(m2m_rig::template::all()?
        .into_iter()
        .map(|template| SkeletonTemplate {
            bones: template.bones().count(),
            chains: template.chains.iter().map(|c| c.name.clone()).collect(),
            available: skeleton_bytes(&template.skeleton).is_some(),
            guidance: template.guidance,
            name: template.name,
        })
        .collect())
}

/// The bytes of an embedded rig, by the file name a manifest gives.
fn skeleton_bytes(name: &str) -> Option<&'static [u8]> {
    SKELETONS
        .iter()
        .find(|(embedded, _)| *embedded == name)
        .map(|(_, bytes)| *bytes)
}

/// Places a named template's skeleton on a model.
///
/// # Errors
///
/// [`RigError`] for an unknown template, a rig that is not bundled, a file that
/// will not read, or a mesh the pipeline cannot place a skeleton on.
pub fn fit(template_name: &str, model: &[u8]) -> Result<FittedSkeleton, RigError> {
    let template = m2m_rig::template::all()?
        .into_iter()
        .find(|t| t.name == template_name)
        .ok_or_else(|| RigError::UnknownTemplate(template_name.to_owned()))?;

    let rig_bytes =
        skeleton_bytes(&template.skeleton).ok_or_else(|| RigError::MissingSkeleton {
            template: template.name.clone(),
            skeleton: template.skeleton.clone(),
        })?;

    let rig = m2m_io::glb::read(rig_bytes)?;
    let TemplateRest {
        rest,
        parents,
        rotations: rest_rotations,
    } = rest_pose(&rig, &template.skeleton)?;
    let mesh = mesh_of(&m2m_io::import::load(model)?);

    // 128 is the resolution the fitting tests use across all nine creatures.
    let fitted: Fitted =
        m2m_rig::fit::fit_template(&template, &rest, &mesh, 128).ok_or(RigError::CannotFit {
            template: template.name.clone(),
        })?;

    // Paired by NAME, not position: `Fitted` is built from the rest pose and
    // keeps its order today, but nothing in either type says it must.
    let rotation_of: std::collections::HashMap<&str, [f32; 4]> = rest
        .bones
        .iter()
        .map(String::as_str)
        .zip(rest_rotations)
        .collect();
    // The template's rest data, in the fitted skeleton's bone order.
    let template_local: Vec<glam::Quat> = fitted
        .bones
        .iter()
        .map(|bone| {
            glam::Quat::from_array(
                rotation_of
                    .get(bone.as_str())
                    .copied()
                    .unwrap_or([0.0, 0.0, 0.0, 1.0]),
            )
        })
        .collect();
    let template_positions: Vec<glam::Vec3> = fitted
        .bones
        .iter()
        .map(|bone| rest.position_of(bone).unwrap_or(glam::Vec3::ZERO))
        .collect();

    // Reorient the rest rotations to match where the arms actually landed, so a
    // template fitted onto a mismatched pose (T-pose rig, A-pose mesh) exports
    // and retargets correctly instead of turning the arms around the template's
    // axis (P3-P3). A fit that already agrees with its template is unchanged.
    let aim = m2m_rig::orient::limb_aims(&template, &fitted.bones);
    let rotations: Vec<[f32; 4]> = m2m_rig::orient::pose_matched_local_rotations(
        &parents,
        &template_positions,
        &template_local,
        &fitted.positions,
        &aim,
    )
    .iter()
    .map(glam::Quat::to_array)
    .collect();

    // The mesh's own up is +Y; the fitted arms drop from horizontal by pose.
    let pose = m2m_rig::pose::pose_of_fitted(&fitted, glam::Vec3::Y)
        .label()
        .to_owned();

    Ok(FittedSkeleton {
        parents,
        positions: fitted.positions.iter().map(|p| p.to_array()).collect(),
        rotations,
        scale: fitted.scale,
        bones: fitted.bones,
        pose,
    })
}

/// What binding produced, without the weights themselves.
///
/// The weights are `vertices x 4` indices and `vertices x 4` floats — about
/// 600 KB for the reference character — so they belong on the bulk channel
/// beside the geometry, not in a JSON reply. Until something draws them, what
/// crosses is the part a person can act on: whether every vertex is attached,
/// and where the solver had to guess.
#[derive(Debug, Serialize, PartialEq)]
pub struct BindReport {
    /// Vertices in the mesh that was bound.
    pub vertices: usize,
    /// Bones allowed to receive weight.
    pub weighted_bones: usize,
    /// Bones excluded because they are the root or a leaf.
    pub excluded_bones: usize,
    /// Vertices no bone reached through the mesh, which fell back to the
    /// nearest bone in a straight line.
    ///
    /// Non-zero means part of the model is a disconnected island — a loose
    /// accessory, or a limb modelled apart from the body. Reported because the
    /// deformation there is a guess, and a guess the user can see is one they
    /// can fix.
    pub fallback_vertices: usize,
    /// How many vertices have 1, 2, 3 or 4 influences.
    pub influence_histogram: [usize; 4],
    /// Vertices with no influence at all.
    ///
    /// Counted separately rather than folded into the histogram's first bucket:
    /// an unweighted vertex is not a lightly-weighted one, it is a vertex that
    /// detaches when the rig moves, and the two must never look alike.
    ///
    /// **This is a canary across a crate boundary, and no test can make it
    /// fire.** `m2m_core::skinning::assign_weights` always writes at least one
    /// influence — a vertex no bone reached takes the straight-line fallback at
    /// weight 1.0 — so nothing that can be fed in produces a non-zero here. A
    /// mutation folding this back into the histogram therefore survives, by
    /// construction rather than for want of a fixture. It stays because the
    /// invariant belongs to another crate and this costs one counter.
    pub unweighted_vertices: usize,
}

/// Binds a mesh to a fitted skeleton.
///
/// # Bone segments
///
/// A bone runs from its own joint **towards its first child**, which is what
/// "the bone" means to anyone looking at it: vertices near the upper arm should
/// follow `upperarm`. The tempting alternative — a segment from the parent's
/// joint down to this one — is off by one, and would weight the shoulder to the
/// upper arm. A branching joint such as the hips has no single continuation and
/// takes its first child in joint order; a leaf bone's segment is a point,
/// which costs nothing because leaves are excluded from weighting anyway.
///
/// # The bone mask
///
/// The root and every leaf are excluded, which is the legacy invariant
/// `m2m_core::skinning::BoneMask` documents: the root carries global transform
/// only, and a leaf exists to orient its parent.
///
/// # Errors
///
/// [`RigError`] for a model that will not read, a mesh that cannot be
/// voxelised, or a skeleton with nothing that may hold weight.
pub fn bind(model: &[u8], skeleton: &FittedSkeleton, falloff: f32) -> Result<BindReport, RigError> {
    Ok(solve(model, skeleton, falloff)?.2)
}

/// The solve behind [`bind`] and [`export_glb`]: mesh, weights and report.
///
/// Export recomputes rather than carrying the weights out to the frontend and
/// back — they are about 600 KB, and the whole solve takes ~56 ms on the
/// reference body. A round trip through the webview would cost more than doing
/// it twice, and there would be a cache to invalidate every time a bone moved.
fn solve(
    model: &[u8],
    skeleton: &FittedSkeleton,
    falloff: f32,
) -> Result<
    (
        m2m_core::mesh::Mesh,
        m2m_core::skinning::SkinWeights,
        BindReport,
    ),
    RigError,
> {
    let mesh = mesh_of(&m2m_io::import::load(model)?);
    if mesh.positions.is_empty() {
        return Err(RigError::NothingToBind {
            reason: "the model has no vertices",
        });
    }

    let mut has_child = vec![false; skeleton.bones.len()];
    for parent in skeleton.parents.iter().flatten() {
        if let Some(slot) = has_child.get_mut(*parent) {
            *slot = true;
        }
    }

    let segments = bone_segments(skeleton);

    // A bone that is neither the root nor a leaf may hold weight.
    let allowed: Vec<bool> = (0..skeleton.bones.len())
        .map(|bone| skeleton.parents.get(bone).copied().flatten().is_some() && has_child[bone])
        .collect();
    let weighted_bones = allowed.iter().filter(|a| **a).count();
    if weighted_bones == 0 {
        return Err(RigError::NothingToBind {
            reason: "every bone is either the root or a leaf",
        });
    }

    let grid = m2m_core::voxel::VoxelGrid::build(&mesh, 128).ok_or(RigError::NothingToBind {
        reason: "the mesh could not be voxelised",
    })?;
    let field = m2m_core::geodesic::GeodesicField::compute(&mesh, &grid, &segments).ok_or(
        RigError::NothingToBind {
            reason: "no bone could reach the mesh",
        },
    )?;

    let weights = m2m_core::skinning::assign_weights(
        &field,
        &mesh.positions,
        &segments,
        &allowed,
        m2m_core::skinning::SkinningParams::new(falloff),
    );

    let mut influence_histogram = [0usize; 4];
    let mut unweighted_vertices = 0usize;
    for vertex in 0..weights.vertex_count() {
        match weights.influences(vertex).count() {
            0 => unweighted_vertices += 1,
            count => {
                if let Some(slot) = influence_histogram.get_mut(count - 1) {
                    *slot += 1;
                }
            }
        }
    }

    let report = BindReport {
        vertices: mesh.positions.len(),
        weighted_bones,
        excluded_bones: skeleton.bones.len() - weighted_bones,
        fallback_vertices: weights.fallback_vertices.len(),
        influence_histogram,
        unweighted_vertices,
    };
    Ok((mesh, weights, report))
}

/// Writes the rigged model as a `.glb`: mesh, skeleton and skin weights.
///
/// # What the exported file is
///
/// The mesh in world space, one node per bone at its fitted position, and a
/// skin binding them. Bone rotations are identity: a fitted skeleton is a set
/// of joint **positions**, and inventing orientations for it would be making up
/// data the fitter never produced. A joint's position is what deforms the mesh,
/// so the export is complete for skinning even though a bone roll is not
/// recovered.
///
/// Inverse bind matrices are the inverse of each bone's world translation,
/// which is exact here because the mesh node carries the identity: the mesh
/// positions are already in world space, so `jointWorld * IBM` is the identity
/// at bind and the mesh does not move until a bone does.
///
/// # Errors
///
/// Whatever the solve produces, plus a write failure from `glb::write`.
/// A per-vertex RGBA weight-paint overlay, four floats per vertex.
///
/// Two things a person needs to see after binding, in one image:
///
/// - **Which bone owns each vertex** — coloured by the vertex's dominant
///   influence, a stable hue per bone index, so the weight regions are visible
///   and a vertex assigned to the wrong bone stands out as a wrong-coloured
///   patch.
/// - **Where the solver guessed** — a vertex the geodesic field could not reach
///   through the mesh took a straight-line fallback, and those are painted a
///   flat flag colour rather than a bone hue. These are the regions to check by
///   hand; `bind` counts them, this shows *where* they are.
///
/// The hue comes from the bone index by the golden-ratio walk of the colour
/// wheel, which keeps adjacent bones far apart in hue without a palette to
/// maintain.
fn weight_colors(weights: &m2m_core::skinning::SkinWeights) -> Vec<f32> {
    // Fallback vertices are a red flag, literally.
    const FLAG: [f32; 4] = [1.0, 0.15, 0.15, 1.0];
    let flagged: std::collections::HashSet<u32> =
        weights.fallback_vertices.iter().copied().collect();

    let mut colors = Vec::with_capacity(weights.vertex_count() * 4);
    for vertex in 0..weights.vertex_count() {
        if flagged.contains(&(vertex as u32)) {
            colors.extend_from_slice(&FLAG);
            continue;
        }
        // The dominant influence: the bone with the greatest weight.
        let dominant = weights
            .influences(vertex)
            .max_by(|a, b| a.1.total_cmp(&b.1))
            .map_or(0, |(bone, _)| bone);
        let [r, g, b] = bone_hue(dominant);
        colors.extend_from_slice(&[r, g, b, 1.0]);
    }
    colors
}

/// A stable, well-spread RGB colour for a bone index.
///
/// The hue advances by the golden angle (0.618 of the wheel) per bone, so
/// consecutive bones — which are usually neighbours in the body — never share a
/// hue, and no palette has to be kept in step with the bone count.
fn bone_hue(bone: u16) -> [f32; 3] {
    let hue = (f32::from(bone) * 0.618_034) % 1.0;
    // HSV to RGB at full saturation and value.
    let h = hue * 6.0;
    let x = 1.0 - (h % 2.0 - 1.0).abs();
    let (r, g, b) = match h as u32 {
        0 => (1.0, x, 0.0),
        1 => (x, 1.0, 0.0),
        2 => (0.0, 1.0, x),
        3 => (0.0, x, 1.0),
        4 => (x, 0.0, 1.0),
        _ => (1.0, 0.0, x),
    };
    [r, g, b]
}

/// Assembles the rigged model into a glTF document: one node per bone, the mesh
/// on a skinned node, plus optional per-vertex `colors` and animation `clips`.
///
/// The exports and the weight-paint overlay all funnel through here, so a bone's
/// placement, its inverse bind matrix and the bind pose are defined once. The
/// mesh's own node carries the skin and the identity transform, which glTF
/// ignores for a skinned node.
fn rigged_document(
    skeleton: &FittedSkeleton,
    mesh: &m2m_core::mesh::Mesh,
    weights: &m2m_core::skinning::SkinWeights,
    colors: Vec<f32>,
    clips: Vec<m2m_io::glb::Clip>,
) -> m2m_io::glb::Document {
    let position = |index: usize| {
        skeleton
            .positions
            .get(index)
            .map_or(glam::Vec3::ZERO, |p| glam::Vec3::from(*p))
    };
    let world_rotation = world_rotations(skeleton);

    // One node per bone. A child's local translation is expressed in its
    // PARENT'S rotated frame, so the composed world lands back on the fitted
    // position — the raw world offset would only work if every bone sat
    // unrotated, which none do.
    let mut nodes: Vec<m2m_io::glb::Node> = skeleton
        .bones
        .iter()
        .enumerate()
        .map(|(bone, name)| {
            let parent = skeleton.parents.get(bone).copied().flatten();
            let offset = position(bone) - parent.map_or(glam::Vec3::ZERO, position);
            let local = match parent {
                Some(parent) => world_rotation[parent].inverse() * offset,
                None => offset,
            };
            m2m_io::glb::Node {
                name: name.clone(),
                parent,
                transform: m2m_io::glb::Trs {
                    translation: local.to_array(),
                    rotation: skeleton
                        .rotations
                        .get(bone)
                        .copied()
                        .unwrap_or([0.0, 0.0, 0.0, 1.0]),
                    scale: [1.0, 1.0, 1.0],
                },
                skin: None,
            }
        })
        .collect();

    let inverse_bind_matrices = (0..skeleton.bones.len())
        .map(|bone| {
            glam::Mat4::from_rotation_translation(world_rotation[bone], position(bone))
                .inverse()
                .to_cols_array()
        })
        .collect();

    let mesh_node = nodes.len();
    nodes.push(m2m_io::glb::Node {
        name: "mesh".into(),
        parent: None,
        transform: m2m_io::glb::Trs {
            translation: [0.0, 0.0, 0.0],
            rotation: [0.0, 0.0, 0.0, 1.0],
            scale: [1.0, 1.0, 1.0],
        },
        skin: Some(0),
    });

    m2m_io::glb::Document {
        primitives: vec![m2m_io::glb::Primitive {
            mesh: 0,
            node: Some(mesh_node),
            positions: mesh.positions.iter().flat_map(|p| p.to_array()).collect(),
            indices: mesh.indices.clone(),
            joints: weights.indices.clone(),
            weights: weights.weights.clone(),
            colors,
        }],
        skins: vec![m2m_io::glb::Skin {
            joints: (0..skeleton.bones.len()).collect(),
            inverse_bind_matrices,
        }],
        nodes,
        clips,
        report: m2m_io::glb::GlbReport::default(),
    }
}

/// Writes the bound model with a weight-paint overlay baked into vertex colours.
///
/// Shares [`solve`] with the exports, so the overlay always shows the weights
/// the export would write — the same one solve, three destinations now.
///
/// # Errors
///
/// Whatever the solve produces, plus a `glb::write` failure.
pub fn overlay_glb(
    model: &[u8],
    skeleton: &FittedSkeleton,
    falloff: f32,
) -> Result<Vec<u8>, RigError> {
    check_bone_order(skeleton)?;
    let (mesh, weights, _) = solve(model, skeleton, falloff)?;
    let colors = weight_colors(&weights);
    let document = rigged_document(skeleton, &mesh, &weights, colors, Vec::new());
    Ok(m2m_io::glb::write(&document)?)
}

pub fn export_glb(
    model: &[u8],
    skeleton: &FittedSkeleton,
    falloff: f32,
    animation: Option<(&[u8], &str)>,
) -> Result<Vec<u8>, RigError> {
    check_bone_order(skeleton)?;
    let (mesh, weights, _) = solve(model, skeleton, falloff)?;

    let clips = match animation {
        Some((library, clip)) => {
            vec![retarget_clip(&m2m_io::glb::read(library)?, skeleton, clip)?]
        }
        None => Vec::new(),
    };
    let document = rigged_document(skeleton, &mesh, &weights, Vec::new(), clips);
    Ok(m2m_io::glb::write(&document)?)
}

/// One clip in a creature's animation library.
#[derive(Debug, Serialize, PartialEq)]
pub struct ClipSummary {
    /// The clip's name, as the library gives it.
    pub name: String,
    /// Longest key time, in seconds.
    pub duration: f32,
    /// Channels the clip drives.
    pub tracks: usize,
}

/// The file names a template's animation library might have, in order.
///
/// Most creatures use `<name>-animations.glb`; the human's base library is
/// `human-base-animations.glb`. Both are tried rather than kept in a table that
/// would drift from the files on disk.
pub fn library_names(template: &str) -> [String; 2] {
    [
        format!("{template}-animations.glb"),
        format!("{template}-base-animations.glb"),
    ]
}

/// The clips a library offers.
///
/// # Errors
///
/// [`RigError::Read`] if the library will not parse.
pub fn library_clips(library: &[u8]) -> Result<Vec<ClipSummary>, RigError> {
    Ok(m2m_io::glb::read(library)?
        .clips
        .into_iter()
        .map(|clip| ClipSummary {
            name: clip.name,
            duration: clip.duration,
            tracks: clip.channels.len(),
        })
        .collect())
}

/// A rig read into the pieces retargeting needs.
struct RetargetSource {
    skeleton: m2m_rig::automap::Skeleton,
    rotations: m2m_rig::retarget::RestRotations,
    translations: m2m_rig::retarget::RestTranslations,
    /// Bone index for each node, so a channel can be pointed at a bone.
    bone_of_node: std::collections::HashMap<usize, usize>,
}

/// Reads a library's own rig: names, parents, positions and rest pose.
fn retarget_source(document: &m2m_io::glb::Document) -> Result<RetargetSource, RigError> {
    let skin = document
        .skins
        .first()
        .ok_or_else(|| RigError::NoSkin("the animation library".to_owned()))?;
    let world = document.world_transforms();
    let slot_of_node: std::collections::HashMap<usize, usize> = skin
        .joints
        .iter()
        .enumerate()
        .map(|(slot, &node)| (node, slot))
        .collect();

    Ok(RetargetSource {
        skeleton: m2m_rig::automap::Skeleton {
            names: skin
                .joints
                .iter()
                .map(|&j| document.nodes[j].name.clone())
                .collect(),
            parents: skin
                .joints
                .iter()
                .map(|&j| {
                    document.nodes[j]
                        .parent
                        .and_then(|p| slot_of_node.get(&p).copied())
                })
                .collect(),
            positions: skin
                .joints
                .iter()
                .map(|&j| world[j].transform_point3(glam::Vec3::ZERO))
                .collect(),
        },
        rotations: m2m_rig::retarget::RestRotations {
            local: skin
                .joints
                .iter()
                .map(|&j| glam::Quat::from_array(document.nodes[j].transform.rotation))
                .collect(),
        },
        translations: m2m_rig::retarget::RestTranslations {
            local: skin
                .joints
                .iter()
                .map(|&j| glam::Vec3::from(document.nodes[j].transform.translation))
                .collect(),
        },
        bone_of_node: slot_of_node,
    })
}

/// Moves one clip from a library onto a fitted skeleton.
///
/// # Why retargeting rather than a copy
///
/// The library and the template look like the same rig and are not. Measured
/// between `rig-human.glb` and `human-base-animations.glb`: **62 of 66 bones
/// carry a different local rest rotation**, the worst by 179.9996 degrees, and
/// the skeletons stand 1.638 m and 1.651 m tall. Copying tracks across would
/// put limbs on backwards.
///
/// Bones are paired **by name**. For the human template that is exactly the
/// identity — measured, the two joint lists match in name *and order* — which
/// means **no fixture here can tell name-pairing from index-pairing**, and a
/// mutation swapping one for the other survives. It stays by name because
/// pairing by position is wrong the moment a library and a template order their
/// joints differently, which nothing prevents; the survivor is a gap in the
/// fixtures, not in the reasoning, and is recorded rather than papered over.
///
/// # Errors
///
/// [`RigError::UnknownClip`] when the library has no such clip.
fn retarget_clip(
    library: &m2m_io::glb::Document,
    skeleton: &FittedSkeleton,
    clip_name: &str,
) -> Result<m2m_io::glb::Clip, RigError> {
    use m2m_rig::retarget::{RotationTrack, TranslationTrack};

    let source = retarget_source(library)?;
    let clip = library
        .clips
        .iter()
        .find(|c| c.name == clip_name)
        .ok_or_else(|| RigError::UnknownClip(clip_name.to_owned()))?;

    let target = m2m_rig::automap::Skeleton {
        names: skeleton.bones.clone(),
        parents: skeleton.parents.clone(),
        positions: skeleton
            .positions
            .iter()
            .map(|p| glam::Vec3::from(*p))
            .collect(),
    };
    let target_rotations = m2m_rig::retarget::RestRotations {
        local: skeleton
            .rotations
            .iter()
            .map(|r| glam::Quat::from_array(*r))
            .collect(),
    };
    let target_translations = m2m_rig::retarget::RestTranslations {
        local: (0..skeleton.bones.len())
            .map(|bone| {
                let position = |i: usize| {
                    skeleton
                        .positions
                        .get(i)
                        .map_or(glam::Vec3::ZERO, |p| glam::Vec3::from(*p))
                };
                let parent = skeleton.parents.get(bone).copied().flatten();
                position(bone) - parent.map_or(glam::Vec3::ZERO, position)
            })
            .collect(),
    };

    // Source bone to target bone, by name.
    let target_of_name: std::collections::HashMap<&str, usize> = skeleton
        .bones
        .iter()
        .enumerate()
        .map(|(index, name)| (name.as_str(), index))
        .collect();
    let mapping: std::collections::HashMap<usize, usize> = source
        .skeleton
        .names
        .iter()
        .enumerate()
        .filter_map(|(bone, name)| target_of_name.get(name.as_str()).map(|&t| (bone, t)))
        .collect();

    let mut rotations = Vec::new();
    let mut translations = Vec::new();
    for channel in &clip.channels {
        let Some(&bone) = source.bone_of_node.get(&channel.node) else {
            continue;
        };
        match channel.path {
            m2m_io::glb::Path::Rotation => rotations.push(RotationTrack {
                bone,
                times: channel.times.clone(),
                rotations: channel
                    .values
                    .chunks_exact(4)
                    .map(|q| glam::Quat::from_xyzw(q[0], q[1], q[2], q[3]))
                    .collect(),
            }),
            m2m_io::glb::Path::Translation => translations.push(TranslationTrack {
                bone,
                times: channel.times.clone(),
                translations: channel
                    .values
                    .chunks_exact(3)
                    .map(|t| glam::Vec3::new(t[0], t[1], t[2]))
                    .collect(),
            }),
            _ => {}
        }
    }

    let (moved, _) = m2m_rig::retarget::retarget(
        &source.skeleton,
        &source.rotations,
        &target,
        &target_rotations,
        &mapping,
        &m2m_rig::retarget::Clip {
            name: clip.name.clone(),
            tracks: rotations,
        },
    );
    let scale = m2m_rig::retarget::height_scale(&source.skeleton, &target);
    let moved_translations = m2m_rig::retarget::retarget_translations(
        &source.translations,
        &target_translations,
        &mapping,
        &translations,
        scale,
    );

    // In the export, bone `i` IS node `i`, so a track's bone is its node.
    let mut channels: Vec<m2m_io::glb::Channel> = moved
        .tracks
        .iter()
        .map(|track| m2m_io::glb::Channel {
            node: track.bone,
            path: m2m_io::glb::Path::Rotation,
            times: track.times.clone(),
            values: track.rotations.iter().flat_map(|q| q.to_array()).collect(),
        })
        .collect();
    channels.extend(moved_translations.iter().map(|track| {
        m2m_io::glb::Channel {
            node: track.bone,
            path: m2m_io::glb::Path::Translation,
            times: track.times.clone(),
            values: track
                .translations
                .iter()
                .flat_map(|t| t.to_array())
                .collect(),
        }
    }));

    Ok(m2m_io::glb::Clip {
        name: clip.name.clone(),
        duration: clip.duration,
        channels,
    })
}

/// Euler curves for a rotation track, in degrees, unwrapped across keys.
///
/// # Why this is not just `to_euler` per key
///
/// FBX stores rotation as three Euler curves; retargeting produces
/// quaternions. `fbx::build`'s own docs call that conversion "lossy and
/// ambiguous", and for a round trip they are right — which is why
/// `examples/rebuild_rig.rs` passes the ORIGINAL curves through untouched. A
/// retargeted clip has no original curves, so the conversion is unavoidable
/// and the ambiguity has to be handled rather than dodged.
///
/// The hazard is not accuracy, it is **continuity**. Every rotation has two
/// Euler triples — `(x, y, z)` and `(x+180, 180-y, z+180)` — and each component
/// is free modulo 360. Taking the canonical triple per key independently can
/// jump a component by a full turn between neighbours, and an importer
/// interpolates that jump as a spin: every key is individually correct and the
/// motion is wrong.
///
/// So each key is chosen to sit nearest its predecessor: both triples are
/// unwrapped to within half a turn of the last key, and the closer one wins.
fn euler_curves(rotations: &[glam::Quat]) -> [Vec<f32>; 3] {
    /// Brings each component within half a turn of `previous`.
    fn unwrap(mut angles: [f32; 3], previous: [f32; 3]) -> [f32; 3] {
        for (angle, last) in angles.iter_mut().zip(previous) {
            *angle += 360.0 * ((last - *angle) / 360.0).round();
        }
        angles
    }
    fn distance(a: [f32; 3], b: [f32; 3]) -> f32 {
        a.iter().zip(b).map(|(x, y)| (x - y).abs()).sum()
    }

    let mut curves = [Vec::new(), Vec::new(), Vec::new()];
    let mut previous: Option<[f32; 3]> = None;
    for rotation in rotations {
        let (x, y, z) = rotation.normalize().to_euler(glam::EulerRot::XYZEx);
        let direct = [x.to_degrees(), y.to_degrees(), z.to_degrees()];
        // The same rotation, expressed the other way round.
        let mirrored = [direct[0] + 180.0, 180.0 - direct[1], direct[2] + 180.0];

        let chosen = match previous {
            None => direct,
            Some(last) => {
                let (a, b) = (unwrap(direct, last), unwrap(mirrored, last));
                if distance(a, last) <= distance(b, last) {
                    a
                } else {
                    b
                }
            }
        };
        previous = Some(chosen);
        for (curve, angle) in curves.iter_mut().zip(chosen) {
            curve.push(angle);
        }
    }
    curves
}

/// One animated property of one bone, owning what `fbx::build` borrows.
struct BuiltCurves {
    bone: usize,
    property: &'static str,
    kind: &'static str,
    times: Vec<i64>,
    values: [Vec<f32>; 3],
}

/// Turns a retargeted clip into FBX channels.
fn fbx_channels(clip: &m2m_io::glb::Clip, bones: usize) -> Vec<BuiltCurves> {
    let ticks = |times: &[f32]| -> Vec<i64> {
        times
            .iter()
            .map(|t| (f64::from(*t) * m2m_io::fbx::animation::FBX_TIME_UNIT) as i64)
            .collect()
    };

    let mut out = Vec::new();
    for channel in &clip.channels {
        if channel.node >= bones {
            continue;
        }
        match channel.path {
            m2m_io::glb::Path::Rotation => {
                let rotations: Vec<glam::Quat> = channel
                    .values
                    .chunks_exact(4)
                    .map(|q| glam::Quat::from_xyzw(q[0], q[1], q[2], q[3]))
                    .collect();
                out.push(BuiltCurves {
                    bone: channel.node,
                    property: "Lcl Rotation",
                    kind: "R",
                    times: ticks(&channel.times),
                    values: euler_curves(&rotations),
                });
            }
            m2m_io::glb::Path::Translation => {
                let mut values = [Vec::new(), Vec::new(), Vec::new()];
                for point in channel.values.chunks_exact(3) {
                    for (curve, axis) in values.iter_mut().zip(point) {
                        // The rest of the FBX export is in centimetres.
                        curve.push(axis * CM_PER_M as f32);
                    }
                }
                out.push(BuiltCurves {
                    bone: channel.node,
                    property: "Lcl Translation",
                    kind: "T",
                    times: ticks(&channel.times),
                    values,
                });
            }
            _ => {}
        }
    }
    out
}

/// Each bone's world rest rotation, composed down the hierarchy.
///
/// One forward pass, which is only correct because a parent always precedes its
/// child — checked by [`check_bone_order`] before either export uses this.
fn world_rotations(skeleton: &FittedSkeleton) -> Vec<glam::Quat> {
    let mut world = vec![glam::Quat::IDENTITY; skeleton.bones.len()];
    for bone in 0..skeleton.bones.len() {
        let local = skeleton
            .rotations
            .get(bone)
            .map_or(glam::Quat::IDENTITY, |r| {
                glam::Quat::from_array(*r).normalize()
            });
        world[bone] = match skeleton.parents.get(bone).copied().flatten() {
            Some(parent) => world[parent] * local,
            None => local,
        };
    }
    world
}

/// Refuses a skeleton whose parent appears after its child.
///
/// `fbx::build` *panics* on it, the world-rotation pass silently gives the
/// wrong answer for it, and a `FittedSkeleton` arrives from the frontend.
/// Measured: all nine shipped rigs are already parents-first, 0 violations of
/// 500 joints — so this guards the boundary, not the assets.
fn check_bone_order(skeleton: &FittedSkeleton) -> Result<(), RigError> {
    for (bone, parent) in skeleton.parents.iter().enumerate() {
        if let Some(parent) = *parent {
            if parent >= bone {
                return Err(RigError::BadBoneOrder { bone, parent });
            }
        }
    }
    Ok(())
}

/// Centimetres per metre. Our meshes are in metres, the glTF convention;
/// `fbx::build` writes `UnitScaleFactor` 1.0, which declares centimetres. Metre
/// values in a file that says centimetres import as a 1.8 cm character.
const CM_PER_M: f64 = 100.0;

/// Writes the rigged model as a binary `.fbx`.
///
/// # Why a second writer rather than a conversion
///
/// FBX is not glTF with different bytes. It counts in the unit its
/// `GlobalSettings` declare, it binds skins with a pair of global matrices
/// rather than one inverse, and it names bones on `Model`/`LimbNode` objects.
/// `m2m_io::fbx::build` already speaks all of that and is verified against
/// Blender; what is missing is the shape of our data in its terms.
///
/// # Two things this must get right
///
/// **Units.** Positions and bone offsets are multiplied by
/// [`CM_PER_M`], because the builder declares centimetres.
///
/// **Cluster inversion.** Weights arrive per vertex, four slots each; FBX wants
/// them per bone, as parallel index and weight lists. A bone that ended up
/// influencing nothing gets no cluster at all rather than an empty one.
///
/// # Errors
///
/// Whatever the solve produces, plus [`RigError::BadBoneOrder`] — `build`
/// *panics* on a parent that appears after its child, and a `FittedSkeleton`
/// arrives from the frontend, so the order is checked here rather than trusted.
pub fn export_fbx(
    model: &[u8],
    skeleton: &FittedSkeleton,
    falloff: f32,
    animation: Option<(&[u8], &str)>,
) -> Result<Vec<u8>, RigError> {
    use m2m_io::fbx::build;

    check_bone_order(skeleton)?;
    let (mesh, weights, _) = solve(model, skeleton, falloff)?;

    let position = |index: usize| {
        skeleton
            .positions
            .get(index)
            .map_or(glam::DVec3::ZERO, |p| {
                glam::DVec3::new(p[0] as f64, p[1] as f64, p[2] as f64) * CM_PER_M
            })
    };

    let world_rotation = world_rotations(skeleton);
    let bones: Vec<build::Bone> = skeleton
        .bones
        .iter()
        .enumerate()
        .map(|(bone, name)| {
            let parent = skeleton.parents.get(bone).copied().flatten();
            let offset = position(bone) - parent.map_or(glam::DVec3::ZERO, position);
            let local = match parent {
                Some(parent) => world_rotation[parent].inverse().as_dquat() * offset,
                None => offset,
            };
            // FBX stores `Lcl Rotation` as Euler degrees, and a model with no
            // `RotationOrder` reads back through `EulerOrder::Zyx`, which
            // `fbx::transform::euler_matrix` composes as `Rz * Ry * Rx`. That
            // is EXTRINSIC XYZ — glam's `XYZEx`. The intrinsic `XYZ` of the
            // same name is a different rotation, and using it put every
            // cluster 82 cm from its bone. Pinned by
            // `an_fbx_euler_round_trip_recovers_the_quaternion`.
            let (x, y, z) = skeleton
                .rotations
                .get(bone)
                .map_or(glam::Quat::IDENTITY, |r| {
                    glam::Quat::from_array(*r).normalize()
                })
                .to_euler(glam::EulerRot::XYZEx);
            build::Bone {
                name,
                parent,
                translation: local.to_array(),
                rotation: [
                    f64::from(x.to_degrees()),
                    f64::from(y.to_degrees()),
                    f64::from(z.to_degrees()),
                ],
                scale: [1.0; 3],
                pre_rotation: [0.0; 3],
            }
        })
        .collect();

    let positions: Vec<f32> = mesh
        .positions
        .iter()
        .flat_map(|p| (*p * CM_PER_M as f32).to_array())
        .collect();
    let meshes = [build::Mesh {
        name: "mesh",
        positions: &positions,
        faces: build::Faces::Triangles(&mesh.indices),
    }];

    // Weights come per vertex with four slots; FBX wants them per bone.
    let mut vertices_of: Vec<Vec<u32>> = vec![Vec::new(); skeleton.bones.len()];
    let mut weights_of: Vec<Vec<f64>> = vec![Vec::new(); skeleton.bones.len()];
    for vertex in 0..weights.vertex_count() {
        for (bone, weight) in weights.influences(vertex) {
            let Some(slot) = vertices_of.get_mut(bone as usize) else {
                continue;
            };
            slot.push(vertex as u32);
            weights_of[bone as usize].push(f64::from(weight));
        }
    }

    // The mesh's global transform at bind is the identity: its positions are
    // already where they sit, so a cluster's `transform` carries nothing.
    let identity = glam::DMat4::IDENTITY.to_cols_array();
    let clusters: Vec<build::Cluster> = (0..skeleton.bones.len())
        .filter(|bone| !vertices_of[*bone].is_empty())
        .map(|bone| build::Cluster {
            bone,
            indices: &vertices_of[bone],
            weights: &weights_of[bone],
            transform: identity,
            transform_link: glam::DMat4::from_rotation_translation(
                world_rotation[bone].as_dquat(),
                position(bone),
            )
            .to_cols_array(),
        })
        .collect();
    let skins = [build::Skin {
        mesh: 0,
        clusters: &clusters,
    }];

    // The clip, in FBX's own terms. Owned here so the borrowed `Curve`s and
    // `Channel`s below outlive the `Scene`.
    let moved = match animation {
        Some((library, name)) => Some(retarget_clip(&m2m_io::glb::read(library)?, skeleton, name)?),
        None => None,
    };
    let built = moved
        .as_ref()
        .map(|clip| fbx_channels(clip, skeleton.bones.len()))
        .unwrap_or_default();

    const AXES: [&str; 3] = ["d|X", "d|Y", "d|Z"];
    let curves: Vec<Vec<build::Curve>> = built
        .iter()
        .map(|entry| {
            entry
                .values
                .iter()
                .enumerate()
                .map(|(axis, values)| build::Curve {
                    axis: AXES[axis],
                    times: &entry.times,
                    values,
                    // Where a curve does not reach, an importer holds this.
                    // Zero is the rest value for both properties, because a
                    // bone's own rest transform already sits on the model.
                    default: 0.0,
                })
                .collect()
        })
        .collect();
    let channels: Vec<build::Channel> = built
        .iter()
        .zip(&curves)
        .map(|(entry, curves)| build::Channel {
            bone: entry.bone,
            property: entry.property,
            kind: entry.kind,
            curves,
        })
        .collect();
    let clips: Vec<build::Clip> = moved
        .as_ref()
        .map(|clip| {
            vec![build::Clip {
                name: &clip.name,
                duration: (f64::from(clip.duration) * m2m_io::fbx::animation::FBX_TIME_UNIT) as i64,
                layer: "Layer0",
                channels: &channels,
            }]
        })
        .unwrap_or_default();

    let scene = build::Scene {
        meshes: &meshes,
        bones: &bones,
        skins: &skins,
        clips: &clips,
        // 30fps. Nothing here is animated, but the field is not optional and a
        // wrong frame rate would misread any clip added later.
        time_mode: 6,
    };

    Ok(m2m_io::fbx::encode::encode(&build::build(&scene))?)
}

/// Each bone as a segment the solver can measure distance to.
///
/// A bone runs from its own joint **towards its first child**. That is what
/// "the bone" means to anyone looking at it: vertices near the upper arm should
/// follow `upperarm`. The tempting alternative — a segment from the parent's
/// joint down to this one — is off by one, and would weight the shoulder to the
/// upper arm.
///
/// A branching joint such as the hips has no single continuation and takes its
/// first child in joint order; that is a judgement call, and the alternatives
/// (a point at the joint, or the average of the children) lose the torso's
/// reach. A leaf's segment is a point, which costs nothing because leaves never
/// hold weight.
fn bone_segments(skeleton: &FittedSkeleton) -> Vec<m2m_core::geodesic::BoneSegment> {
    let position = |index: usize| {
        skeleton
            .positions
            .get(index)
            .map_or(glam::Vec3::ZERO, |p| glam::Vec3::from(*p))
    };
    (0..skeleton.bones.len())
        .map(|bone| {
            let head = position(bone);
            let tail = skeleton
                .parents
                .iter()
                .position(|p| *p == Some(bone))
                .map_or(head, position);
            m2m_core::geodesic::BoneSegment { head, tail }
        })
        .collect()
}

/// A rig's joints as a rest pose, plus each joint's parent within the joint list.
///
/// A joint's parent is its parent **node**, looked up in the joint list. That
/// is only correct while no rig puts a plain node in the middle of a bone
/// chain, and all nine shipped rigs satisfy it — measured: the direct-parent
/// rule and a full nearest-joint-ancestor walk agree on every joint of every
/// rig, and each has exactly one root. The walk was written first and removed
/// once the measurement showed it was untested defensive code;
/// `every_rig_hangs_its_bones_directly_off_each_other` is what fails if a
/// future asset breaks the assumption.
/// A template rig read into the three things fitting and export need.
struct TemplateRest {
    /// Bone names and their world rest positions.
    rest: RestPose,
    /// Each bone's parent, as an index into the joint list.
    parents: Vec<Option<usize>>,
    /// Each bone's local rest rotation, xyzw.
    rotations: Vec<[f32; 4]>,
}

fn rest_pose(document: &m2m_io::glb::Document, name: &str) -> Result<TemplateRest, RigError> {
    let skin = document
        .skins
        .first()
        .ok_or_else(|| RigError::NoSkin(name.to_owned()))?;
    let world = document.world_transforms();

    let mut joint_of = vec![None; document.nodes.len()];
    for (slot, &node) in skin.joints.iter().enumerate() {
        if let Some(entry) = joint_of.get_mut(node) {
            *entry = Some(slot);
        }
    }

    let parents = skin
        .joints
        .iter()
        .map(|&node| {
            let parent = document.nodes.get(node)?.parent?;
            joint_of.get(parent).copied().flatten()
        })
        .collect();

    let rest = RestPose {
        bones: skin
            .joints
            .iter()
            .filter_map(|&j| document.nodes.get(j).map(|n| n.name.clone()))
            .collect(),
        positions: skin
            .joints
            .iter()
            .filter_map(|&j| world.get(j).map(|m| m.transform_point3(glam::Vec3::ZERO)))
            .collect(),
    };
    let rotations = skin
        .joints
        .iter()
        .filter_map(|&j| document.nodes.get(j).map(|n| n.transform.rotation))
        .collect();
    Ok(TemplateRest {
        rest,
        parents,
        rotations,
    })
}

/// A document's geometry as one mesh in world space.
fn mesh_of(document: &m2m_io::glb::Document) -> m2m_core::mesh::Mesh {
    let world = document.world_transforms();
    let mut mesh = m2m_core::mesh::Mesh::default();
    for primitive in &document.primitives {
        let transform = primitive
            .node
            .and_then(|n| world.get(n).copied())
            .unwrap_or(glam::Mat4::IDENTITY);
        let base = mesh.positions.len() as u32;
        for chunk in primitive.positions.chunks_exact(3) {
            mesh.positions
                .push(transform.transform_point3(glam::Vec3::new(chunk[0], chunk[1], chunk[2])));
        }
        mesh.indices
            .extend(primitive.indices.iter().map(|i| i + base));
    }
    mesh
}

#[cfg(test)]
mod tests {
    use super::{fit, templates};

    fn model(relative: &str) -> Vec<u8> {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../assets/").to_owned() + relative;
        std::fs::read(&path).unwrap_or_else(|e| panic!("reading {path}: {e}"))
    }

    #[test]
    fn every_shipped_template_has_the_rig_it_names() {
        // A manifest naming a `.glb` that is not embedded would fail only when
        // a user picked that creature, which is the worst time to find out.
        let offered = templates().expect("the shipped manifests parse");

        assert_eq!(offered.len(), 15);
        for template in &offered {
            assert!(template.available, "{} has no bundled rig", template.name);
            assert!(template.bones > 0, "{} claims no bones", template.name);
            assert!(
                !template.chains.is_empty(),
                "{} has no chains",
                template.name
            );
        }
        assert_eq!(offered.iter().map(|t| t.bones).sum::<usize>(), 715);
    }

    #[test]
    fn fitting_places_the_human_rig_on_a_human_mesh() {
        let fitted = fit("human", &model("models/model-human.glb")).expect("fits");

        assert_eq!(fitted.bones.len(), 66);
        assert_eq!(fitted.positions.len(), 66);
        assert_eq!(fitted.parents.len(), 66);
        assert!(fitted.bones.contains(&"pelvis".to_owned()));

        // The model is 1.83 m tall and the rig was authored at the same scale,
        // so a fit that had to scale by 10 would mean the units were wrong.
        assert!(
            (0.5..2.0).contains(&fitted.scale),
            "scale {} is not plausible",
            fitted.scale
        );
    }

    #[test]
    fn exactly_one_bone_is_a_root_and_every_other_parent_is_real() {
        // A skeleton is drawn as segments from each bone to its parent, so a
        // parent index that is out of range, or a second root, is a hole in
        // the drawing rather than an error anyone would see.
        let fitted = fit("human", &model("models/model-human.glb")).expect("fits");

        let roots = fitted.parents.iter().filter(|p| p.is_none()).count();
        assert_eq!(roots, 1, "expected one root, got {roots}");
        for (index, parent) in fitted.parents.iter().enumerate() {
            let Some(parent) = *parent else { continue };
            assert!(
                parent < fitted.bones.len(),
                "bone {index} has no such parent"
            );
            assert_ne!(parent, index, "bone {index} is its own parent");
        }
    }

    /// Every shipped rig hangs each bone directly off another bone.
    #[test]
    fn every_rig_hangs_its_bones_directly_off_each_other() {
        // What `rest_pose`'s parent lookup assumes. A rig with a plain node in
        // the middle of a chain would silently produce a second root and a
        // skeleton drawn with a hole in it, so the assumption is asserted
        // rather than trusted.
        for template in templates().expect("manifests parse") {
            let fitted = fit(&template.name, &model("models/model-human.glb"));
            // Fitting a human mesh with a shark rig is allowed to fail; the
            // parent structure is what is under test, so read it directly.
            let Ok(fitted) = fitted else { continue };
            assert_eq!(
                fitted.parents.iter().filter(|p| p.is_none()).count(),
                1,
                "{} does not have exactly one root",
                template.name
            );
        }
    }

    /// A bone points at its child, not back at its parent.
    #[test]
    fn a_bone_runs_from_its_own_joint_towards_its_child() {
        use super::{bone_segments, FittedSkeleton};

        // A three-bone chain at 0, 1 and 2 on Y.
        let skeleton = FittedSkeleton {
            bones: vec!["root".into(), "middle".into(), "tip".into()],
            parents: vec![None, Some(0), Some(1)],
            positions: vec![[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 2.0, 0.0]],
            rotations: vec![
                [0.0, 0.0, 0.0, 1.0],
                [0.0, 0.0, 0.0, 1.0],
                [0.0, 0.0, 0.0, 1.0],
            ],
            scale: 1.0,
            pose: "other".into(),
        };
        let segments = bone_segments(&skeleton);

        // Reversing the convention gives head 1 tail 0 here, which is why the
        // heads are asserted too and not only the tails.
        assert_eq!(segments[0].head, glam::Vec3::ZERO);
        assert_eq!(segments[0].tail, glam::Vec3::new(0.0, 1.0, 0.0));
        assert_eq!(segments[1].head, glam::Vec3::new(0.0, 1.0, 0.0));
        assert_eq!(segments[1].tail, glam::Vec3::new(0.0, 2.0, 0.0));
        // A leaf has no child, so its segment is a point rather than a
        // backwards line.
        assert_eq!(segments[2].head, segments[2].tail);
        assert_eq!(segments[2].head, glam::Vec3::new(0.0, 2.0, 0.0));
    }

    /// Binding attaches every vertex to something.
    #[test]
    fn binding_leaves_no_vertex_behind() {
        // `m2m_core::skinning`'s first invariant: an unweighted vertex detaches
        // when the rig moves. Measured on the reference body — 7,399 vertices,
        // none unweighted, none needing the straight-line fallback because the
        // mesh is one connected piece.
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let report = super::bind(
            &model("models/model-human.glb"),
            &skeleton,
            m2m_core::skinning::DEFAULT_FALLOFF,
        )
        .expect("binds");

        assert_eq!(report.vertices, 7399);
        assert_eq!(report.unweighted_vertices, 0);
        assert_eq!(report.fallback_vertices, 0);
        assert_eq!(
            report.influence_histogram.iter().sum::<usize>(),
            report.vertices,
            "every vertex is in exactly one bucket"
        );
        // Measured, and recorded because it is a large difference in character
        // from a hand-authored rig: the geodesic solver gives 96% of vertices
        // the full four influences, where the reference Mixamo export gives 93%
        // of its vertices exactly one. Whether that is too smooth is what the
        // legacy A/B in `memory/test.md` §9 is for.
        assert_eq!(report.influence_histogram, [254, 3, 38, 7104]);
    }

    /// The root and every leaf are kept out of the weighting.
    #[test]
    fn only_bones_between_the_root_and_the_leaves_hold_weight() {
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let report = super::bind(
            &model("models/model-human.glb"),
            &skeleton,
            m2m_core::skinning::DEFAULT_FALLOFF,
        )
        .expect("binds");

        // Recomputed from the skeleton rather than hardcoded, so this says what
        // the rule IS, not merely what it counted to on one rig.
        let has_child: Vec<bool> = (0..skeleton.bones.len())
            .map(|bone| skeleton.parents.contains(&Some(bone)))
            .collect();
        let expected = (0..skeleton.bones.len())
            .filter(|&b| skeleton.parents[b].is_some() && has_child[b])
            .count();

        assert_eq!(report.weighted_bones, expected);
        assert_eq!(
            report.weighted_bones + report.excluded_bones,
            skeleton.bones.len()
        );
        // One root and thirteen leaves on the human rig.
        assert_eq!(report.excluded_bones, 14);
    }

    /// A skeleton with nothing between root and leaf cannot hold weight.
    #[test]
    fn a_skeleton_with_no_weightable_bone_is_refused() {
        use super::FittedSkeleton;

        // Two bones: a root and its leaf. Neither may hold weight, so binding
        // has nothing to assign and must say so rather than assert its way out
        // of `assign_weights`, which panics on an empty mask.
        let skeleton = FittedSkeleton {
            bones: vec!["root".into(), "tip".into()],
            parents: vec![None, Some(0)],
            positions: vec![[0.0, 0.0, 0.0], [0.0, 1.0, 0.0]],
            rotations: vec![[0.0, 0.0, 0.0, 1.0], [0.0, 0.0, 0.0, 1.0]],
            scale: 1.0,
            pose: "other".into(),
        };
        let err = super::bind(
            &model("models/model-human.glb"),
            &skeleton,
            m2m_core::skinning::DEFAULT_FALLOFF,
        )
        .expect_err("refused");

        assert!(
            matches!(err, super::RigError::NothingToBind { .. }),
            "got {err:?}"
        );
    }

    /// A cube of `size`, centred at `at`, as positions and triangle indices.
    fn cube(at: glam::Vec3, size: f32) -> (Vec<f32>, Vec<u32>) {
        let h = size / 2.0;
        let mut positions = Vec::with_capacity(24);
        for corner in 0..8 {
            let sign = |bit: u32| if corner & (1 << bit) == 0 { -h } else { h };
            positions.extend_from_slice(&[at.x + sign(0), at.y + sign(1), at.z + sign(2)]);
        }
        // Two triangles per face, wound consistently enough to voxelise.
        const FACES: [[u32; 4]; 6] = [
            [0, 1, 3, 2],
            [4, 6, 7, 5],
            [0, 4, 5, 1],
            [2, 3, 7, 6],
            [0, 2, 6, 4],
            [1, 5, 7, 3],
        ];
        let mut indices = Vec::with_capacity(36);
        for f in FACES {
            indices.extend_from_slice(&[f[0], f[1], f[2], f[0], f[2], f[3]]);
        }
        (positions, indices)
    }

    /// A `.glb` of two cubes, far enough apart to share no voxels.
    fn two_islands() -> Vec<u8> {
        let mut document = m2m_io::glb::Document {
            nodes: Vec::new(),
            primitives: Vec::new(),
            skins: Vec::new(),
            clips: Vec::new(),
            report: m2m_io::glb::GlbReport::default(),
        };
        document.nodes.push(m2m_io::glb::Node {
            name: "islands".into(),
            parent: None,
            transform: m2m_io::glb::Trs {
                translation: [0.0, 0.0, 0.0],
                rotation: [0.0, 0.0, 0.0, 1.0],
                scale: [1.0, 1.0, 1.0],
            },
            skin: None,
        });
        for (mesh, at) in [glam::Vec3::ZERO, glam::Vec3::new(10.0, 0.0, 0.0)]
            .into_iter()
            .enumerate()
        {
            let (positions, indices) = cube(at, 1.0);
            document.primitives.push(m2m_io::glb::Primitive {
                mesh,
                node: Some(0),
                positions,
                indices,
                joints: Vec::new(),
                weights: Vec::new(),
                colors: Vec::new(),
            });
        }
        m2m_io::glb::write(&document).expect("writes")
    }

    /// A model in two pieces gets its far piece attached, and says so.
    #[test]
    fn a_disconnected_island_is_attached_by_the_fallback_and_reported() {
        // The geodesic field spreads through the VOXEL GRID, not mesh
        // topology, so separate meshes that sit next to each other are still
        // reachable — measured: the nine-mesh reference character reports zero
        // fallbacks. Only geometry with real empty space around it, like a
        // prop modelled away from the body, takes this path.
        let skeleton = super::FittedSkeleton {
            bones: vec!["root".into(), "body".into(), "tip".into()],
            parents: vec![None, Some(0), Some(1)],
            positions: vec![[0.0, -0.4, 0.0], [0.0, 0.0, 0.0], [0.0, 0.4, 0.0]],
            rotations: vec![
                [0.0, 0.0, 0.0, 1.0],
                [0.0, 0.0, 0.0, 1.0],
                [0.0, 0.0, 0.0, 1.0],
            ],
            scale: 1.0,
            pose: "other".into(),
        };

        let report = super::bind(&two_islands(), &skeleton, 2.0).expect("binds");

        // The far cube's eight corners cannot be reached through the mesh.
        assert_eq!(report.fallback_vertices, 8, "{report:?}");
        // Attached all the same: a guessed bone beats detaching.
        assert_eq!(report.unweighted_vertices, 0);
        assert_eq!(
            report.influence_histogram.iter().sum::<usize>(),
            report.vertices
        );
    }

    /// The exported file is a rigged model any glTF reader can open.
    #[test]
    fn the_export_carries_the_mesh_the_skeleton_and_the_weights() {
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes = super::export_glb(&model("models/model-human.glb"), &skeleton, 2.0, None)
            .expect("exports");

        // Written so the Blender and assimp checks have something to open.
        let path = std::env::temp_dir().join("m2m-export-check.glb");
        std::fs::write(&path, &bytes).expect("writes");
        println!("wrote {}", path.display());

        let back = m2m_io::glb::read(&bytes).expect("reads back");
        assert_eq!(back.skins.len(), 1);
        assert_eq!(back.skins[0].joints.len(), skeleton.bones.len());
        assert_eq!(
            back.skins[0].inverse_bind_matrices.len(),
            skeleton.bones.len(),
            "a joint without a bind matrix binds to the identity"
        );
        assert_eq!(back.nodes.len(), skeleton.bones.len() + 1);
        assert_eq!(back.primitives.len(), 1);

        // glTF puts the skin on the NODE, not the mesh. A file with an
        // armature and a mesh that references no skin imports unweighted —
        // `glb::Node`'s own docs warn about exactly this — and every count
        // above still looks right when the link is missing.
        let skinned: Vec<usize> = back
            .nodes
            .iter()
            .enumerate()
            .filter(|(_, node)| node.skin == Some(0))
            .map(|(index, _)| index)
            .collect();
        assert_eq!(skinned.len(), 1, "exactly one node must carry the skin");
        assert_eq!(
            back.primitives[0].node,
            Some(skinned[0]),
            "the primitive must hang off the node that carries the skin"
        );

        // Every vertex carries four influence slots, and they still sum to one
        // after the round trip through the file.
        let primitive = &back.primitives[0];
        let vertices = primitive.positions.len() / 3;
        assert_eq!(primitive.joints.len(), vertices * 4);
        for vertex in primitive.weights.chunks_exact(4) {
            let total: f32 = vertex.iter().sum();
            assert!((total - 1.0).abs() < 1e-3, "weights sum to {total}");
        }
    }

    /// The exported skeleton stands where the fitter put it.
    #[test]
    fn a_bones_world_position_survives_the_export() {
        // Bone nodes carry OFFSETS from their parent, so a version that wrote
        // world positions as local ones would look right in a flat scene and
        // pile every bone on top of the last in a deep chain.
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes = super::export_glb(&model("models/model-human.glb"), &skeleton, 2.0, None)
            .expect("exports");
        let back = m2m_io::glb::read(&bytes).expect("reads back");
        let world = back.world_transforms();

        let mut worst = 0.0f32;
        for (bone, expected) in skeleton.positions.iter().enumerate() {
            let got = world[bone].transform_point3(glam::Vec3::ZERO);
            worst = worst.max(got.distance(glam::Vec3::from(*expected)));
        }
        assert!(worst < 1e-4, "worst bone moved {worst} m in the export");
    }

    /// The bind pose is the identity: the mesh does not move until a bone does.
    #[test]
    fn the_exported_mesh_sits_still_in_its_bind_pose() {
        // `jointWorld * IBM` must be the identity, or the model deforms the
        // instant it is opened — which no count of bones or vertices reveals.
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes = super::export_glb(&model("models/model-human.glb"), &skeleton, 2.0, None)
            .expect("exports");
        let back = m2m_io::glb::read(&bytes).expect("reads back");
        let world = back.world_transforms();

        let mut worst = 0.0f32;
        for (slot, &joint) in back.skins[0].joints.iter().enumerate() {
            let ibm = glam::Mat4::from_cols_array(&back.skins[0].inverse_bind_matrices[slot]);
            let product = world[joint] * ibm;
            for (a, b) in product
                .to_cols_array()
                .iter()
                .zip(glam::Mat4::IDENTITY.to_cols_array().iter())
            {
                worst = worst.max((a - b).abs());
            }
        }
        assert!(worst < 1e-5, "bind pose is off by {worst}");
    }

    /// The FBX export carries the same rig, in the units it declares.
    #[test]
    fn the_fbx_export_declares_centimetres_and_uses_them() {
        // `fbx::build` writes UnitScaleFactor 1.0, which means centimetres.
        // Metre values in that file import as a 1.8 cm character, and no count
        // of bones or vertices would show it.
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes = super::export_fbx(&model("models/model-human.glb"), &skeleton, 2.0, None)
            .expect("exports");

        let path = std::env::temp_dir().join("m2m-export-check.fbx");
        std::fs::write(&path, &bytes).expect("writes");
        println!("wrote {}", path.display());

        let scene = m2m_io::fbx::dom::Scene::from_document(
            m2m_io::fbx::binary::parse(&bytes).expect("our own reader reads it"),
        );
        assert_eq!(scene.unit_scale, Some(1.0), "the file declares centimetres");

        let models = m2m_io::fbx::model::parse_all(&scene);
        let bones: Vec<&m2m_io::fbx::model::Model> =
            models.models.iter().filter(|m| m.is_bone()).collect();
        assert_eq!(bones.len(), 66);

        // A human is 1.2 to 2.5 m, which in this file must read as 120 to 250.
        let ys: Vec<f64> = bones
            .iter()
            .map(|b| b.world.transform_point3(glam::DVec3::ZERO).y)
            .collect();
        let height = ys.iter().copied().fold(f64::MIN, f64::max)
            - ys.iter().copied().fold(f64::MAX, f64::min);
        assert!(
            (100.0..250.0).contains(&height),
            "skeleton spans {height} file units, which is not a character in centimetres"
        );

        // And the MESH, in the same units. Scaling the bones without the
        // geometry leaves a skeleton a hundred times the size of the body it
        // is meant to deform, and the skeleton assertion above still passes.
        let geometry = scene.objects_of_kind("Geometry");
        let mesh = m2m_io::fbx::geometry::parse(
            geometry.first().expect("a geometry"),
            m2m_io::fbx::geometry::GeometricTransform::default(),
        )
        .expect("parses");
        let mesh_ys: Vec<f32> = mesh.positions.chunks_exact(3).map(|p| p[1]).collect();
        let mesh_height = mesh_ys.iter().copied().fold(f32::MIN, f32::max)
            - mesh_ys.iter().copied().fold(f32::MAX, f32::min);
        assert!(
            (100.0..250.0).contains(&mesh_height),
            "mesh spans {mesh_height} file units against the skeleton's {height}"
        );
    }

    /// The exported skeleton keeps the template's rest rotations.
    #[test]
    fn the_export_keeps_the_rest_rotations_the_template_carries() {
        // Measured: all 66 bones of `rig-human.glb` carry a non-identity local
        // rotation, up to 179.94 degrees. Writing identity instead loses bone
        // roll and puts every clip authored against the template out of
        // alignment — and EVERY bind-pose assertion still passes, because they
        // are self-consistent about whatever rotations they are given. Only
        // comparing against the template catches it.
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");

        let turned = skeleton
            .rotations
            .iter()
            .filter(|r| {
                glam::Quat::from_array(**r).normalize().to_axis_angle().1 > 0.01_f32.to_radians()
            })
            .count();
        assert_eq!(turned, 66, "the fit dropped the template's rest rotations");

        let bytes = super::export_glb(&model("models/model-human.glb"), &skeleton, 2.0, None)
            .expect("exports");
        let back = m2m_io::glb::read(&bytes).expect("reads back");
        for (bone, expected) in skeleton.rotations.iter().enumerate() {
            let written = glam::Quat::from_array(back.nodes[bone].transform.rotation);
            let expected = glam::Quat::from_array(*expected).normalize();
            assert!(
                written.abs_diff_eq(expected, 1e-5) || written.abs_diff_eq(-expected, 1e-5),
                "bone {bone} was written as {written:?}, not {expected:?}"
            );
        }
    }

    fn library() -> Vec<u8> {
        model("animations/human-base-animations.glb")
    }

    /// Every template the app offers has an animation library to draw on.
    #[test]
    fn every_shipped_template_has_a_library_the_bundle_will_carry() {
        // `tauri.conf.json` globs `assets/animations/*.glb` into the
        // bundle. A template whose library is missing would list no clips only
        // when a user picked that creature — the same failure mode `available`
        // exists to prevent for rigs.
        let directory = concat!(env!("CARGO_MANIFEST_DIR"), "/../../assets/animations");
        for template in templates().expect("manifests parse") {
            let found = super::library_names(&template.name)
                .iter()
                .any(|name| std::path::Path::new(directory).join(name).is_file());
            assert!(found, "no animation library for {}", template.name);
        }
    }

    // `the_bundle_config_carries_the_animation_libraries` moved to `src-tauri`
    // with the extraction: it validates the app's `tauri.conf.json`, which is not
    // this crate's file.

    /// The human's library is the `-base-` one, which is why two names are tried.
    #[test]
    fn the_human_library_is_found_under_its_second_name() {
        let directory = std::path::Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../assets/animations"
        ));
        let [first, second] = super::library_names("human");

        assert!(
            !directory.join(&first).is_file(),
            "{first} exists, so the fallback is no longer exercised"
        );
        assert!(directory.join(&second).is_file(), "{second} is missing");
        // And a creature that uses the FIRST name, so both branches are live.
        assert!(directory.join(&super::library_names("fox")[0]).is_file());
    }

    #[test]
    fn the_library_offers_its_clips() {
        let clips = super::library_clips(&library()).expect("lists");

        assert_eq!(clips.len(), 94);
        assert_eq!(clips[0].name, "Chest_Open");
        assert!((clips[0].duration - 1.375).abs() < 1e-3, "{:?}", clips[0]);
        assert!(clips.iter().all(|c| c.duration > 0.0 && c.tracks > 0));
    }

    /// An animated export keeps the clip's TIME AXIS, not merely its keys.
    #[test]
    fn an_animated_export_keeps_the_clips_time_axis() {
        // Counting keys proves nothing: retargeting resamples onto the union of
        // key times, so the count legitimately changes. What must NOT change is
        // when the motion starts and ends — a clip that plays 20% slow has
        // every other number identical.
        let source = m2m_io::glb::read(&library()).expect("reads");
        let chest = source
            .clips
            .iter()
            .find(|c| c.name == "Chest_Open")
            .expect("the fixture has this clip");
        // PER PATH. Taking min/max across every channel lets one path's
        // untouched times hide another's: scaling only the rotation times by
        // 0.8 left the span correct, because the translation channels still
        // reached the end.
        let span = |clip: &m2m_io::glb::Clip, path: m2m_io::glb::Path| {
            let times: Vec<f32> = clip
                .channels
                .iter()
                .filter(|c| c.path == path)
                .flat_map(|c| c.times.clone())
                .collect();
            assert!(!times.is_empty(), "no {path:?} channels to measure");
            (
                times.iter().copied().fold(f32::MAX, f32::min),
                times.iter().copied().fold(f32::MIN, f32::max),
            )
        };

        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes = super::export_glb(
            &model("models/model-human.glb"),
            &skeleton,
            2.0,
            Some((&library(), "Chest_Open")),
        )
        .expect("exports");

        let path = std::env::temp_dir().join("m2m-animated.glb");
        std::fs::write(&path, &bytes).expect("writes");

        let back = m2m_io::glb::read(&bytes).expect("reads back");
        assert_eq!(back.clips.len(), 1);
        let out = &back.clips[0];
        assert_eq!(out.name, "Chest_Open");

        for path in [m2m_io::glb::Path::Rotation, m2m_io::glb::Path::Translation] {
            let (source_start, source_end) = span(chest, path);
            let (out_start, out_end) = span(out, path);
            assert!(
                (out_start - source_start).abs() < 1e-4,
                "{path:?} starts at {out_start}, source at {source_start}"
            );
            assert!(
                (out_end - source_end).abs() < 1e-4,
                "{path:?} ends at {out_end}, source at {source_end}"
            );
        }
        assert!((out.duration - chest.duration).abs() < 1e-4);

        // 66 rotation and 66 translation channels. The source's 66 SCALE
        // channels are dropped: `retarget` moves rotation and translation, and
        // a scaled bone is not something the fitter or the solver produce.
        assert_eq!(out.channels.len(), 132);
        assert!(out.channels.iter().all(|c| matches!(
            c.path,
            m2m_io::glb::Path::Rotation | m2m_io::glb::Path::Translation
        )));

        // Every channel drives a bone node that exists.
        assert!(out.channels.iter().all(|c| c.node < skeleton.bones.len()));
    }

    /// Retargeting actually moves the motion; it is not a rename.
    #[test]
    fn the_exported_rotations_are_retargeted_not_copied() {
        // The decisive property, and the one every count misses: a verbatim
        // copy produces the same clip name, the same channel count and the same
        // time axis, while putting limbs up to 180 degrees wrong. Two-sided on
        // purpose — bones whose rest poses AGREE must come through unchanged,
        // so a retarget that mangles everything fails this too.
        let library_document = m2m_io::glb::read(&library()).expect("reads");
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let source = super::retarget_source(&library_document).expect("reads the rig");

        let bytes = super::export_glb(
            &model("models/model-human.glb"),
            &skeleton,
            2.0,
            Some((&library(), "Chest_Open")),
        )
        .expect("exports");
        let read_back = m2m_io::glb::read(&bytes).expect("reads back");
        let out = &read_back.clips[0];

        let chest = library_document
            .clips
            .iter()
            .find(|c| c.name == "Chest_Open")
            .expect("clip");
        let first_source: std::collections::HashMap<usize, glam::Quat> = chest
            .channels
            .iter()
            .filter(|c| c.path == m2m_io::glb::Path::Rotation)
            .filter_map(|c| {
                let bone = *source.bone_of_node.get(&c.node)?;
                let q = c.values.get(..4)?;
                Some((bone, glam::Quat::from_xyzw(q[0], q[1], q[2], q[3])))
            })
            .collect();

        let angle = |a: glam::Quat, b: glam::Quat| {
            let (a, b) = (a.normalize(), b.normalize());
            a.angle_between(if a.dot(b) < 0.0 { -b } else { b })
                .to_degrees()
        };

        let mut moved = 0usize;
        let mut held_where_rest_agrees = 0usize;
        for channel in out
            .channels
            .iter()
            .filter(|c| c.path == m2m_io::glb::Path::Rotation)
        {
            let (Some(before), Some(q)) =
                (first_source.get(&channel.node), channel.values.get(..4))
            else {
                continue;
            };
            let after = glam::Quat::from_xyzw(q[0], q[1], q[2], q[3]);
            let rest_gap = angle(
                source.rotations.local[channel.node],
                glam::Quat::from_array(skeleton.rotations[channel.node]),
            );

            if angle(*before, after) > 1.0 {
                moved += 1;
            } else if rest_gap < 0.01 {
                held_where_rest_agrees += 1;
            }
        }

        // 62 of 66 rest rotations differ, so most bones must have moved.
        assert!(
            moved > 50,
            "only {moved} rotations changed — this is a copy"
        );
        assert!(
            held_where_rest_agrees > 0,
            "every bone moved, including those whose rest poses already agree"
        );
    }

    #[test]
    fn a_clip_the_library_does_not_have_is_refused() {
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let err = super::export_glb(
            &model("models/model-human.glb"),
            &skeleton,
            2.0,
            Some((&library(), "Moonwalk")),
        )
        .expect_err("refused");

        assert!(
            matches!(err, super::RigError::UnknownClip(name) if name == "Moonwalk"),
            "wrong error"
        );
    }

    /// Retargeting is not a copy: the two rigs' rest poses genuinely differ.
    #[test]
    fn the_library_and_the_template_do_not_share_a_rest_pose() {
        // Measured: 62 of 66 bones carry a different local rest rotation, the
        // worst by 179.9996 degrees. If this ever became 0, retargeting would
        // be a copy and the machinery would be unnecessary — which is worth
        // knowing rather than assuming in either direction.
        let library = m2m_io::glb::read(&library()).expect("reads");
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let source = super::retarget_source(&library).expect("reads the rig");

        let differing = source
            .rotations
            .local
            .iter()
            .zip(skeleton.rotations.iter())
            .filter(|(a, b)| {
                let b = glam::Quat::from_array(**b).normalize();
                let a = a.normalize();
                a.angle_between(if a.dot(b) < 0.0 { -b } else { b }) > 0.01_f32.to_radians()
            })
            .count();
        assert_eq!(differing, 62, "the rest poses moved relative to each other");
    }

    /// Every key reconstructs, and no neighbour jumps.
    #[test]
    fn euler_curves_reconstruct_each_key_without_jumping_between_them() {
        // Two-sided, because each half alone is satisfiable by a broken
        // conversion: taking the canonical triple per key reconstructs
        // perfectly and can still jump a full turn between neighbours, which an
        // importer interpolates as a spin. A full turn about Y is the case that
        // forces it — the middle angle of an XYZ Euler is confined to a
        // quarter turn, so continuing past it MUST switch branches.
        // About a TILTED axis, so all three Euler components are non-zero. A
        // pure Y spin cannot tell intrinsic XYZ from extrinsic: for a
        // single-axis rotation the two orders agree, and a mutation swapping
        // them survives.
        let axis = glam::Vec3::new(0.3, 1.0, 0.2).normalize();
        let rotations: Vec<glam::Quat> = (0..=72)
            .map(|step| glam::Quat::from_axis_angle(axis, step as f32 * 5.0_f32.to_radians()))
            .collect();
        let curves = super::euler_curves(&rotations);

        let mut worst_error = 0.0f32;
        let mut worst_jump = 0.0f32;
        for key in 0..rotations.len() {
            let (x, y, z) = (curves[0][key], curves[1][key], curves[2][key]);
            let rebuilt = glam::Quat::from_mat4(
                &(glam::Mat4::from_rotation_z(z.to_radians())
                    * glam::Mat4::from_rotation_y(y.to_radians())
                    * glam::Mat4::from_rotation_x(x.to_radians())),
            );
            let expected = rotations[key];
            let signed = if rebuilt.dot(expected) < 0.0 {
                -expected
            } else {
                expected
            };
            worst_error = worst_error.max(rebuilt.angle_between(signed).to_degrees());

            if key > 0 {
                for curve in &curves {
                    worst_jump = worst_jump.max((curve[key] - curve[key - 1]).abs());
                }
            }
        }

        // Measured 0.056 degrees, and it is gimbal lock rather than sloppiness:
        // a pure Y spin passes exactly through y = 90, where an XYZ Euler's
        // outer angles become ill-conditioned and f32 degrees lose precision.
        // This is the worst case by construction; real motion rarely sits on
        // the singularity, and 0.06 degrees is far below anything visible.
        assert!(worst_error < 0.1, "a key is off by {worst_error} degrees");
        // Each step is 5 degrees, so a well-chosen branch never moves far. A
        // canonical-per-key conversion jumps 180 here.
        assert!(worst_jump < 90.0, "a neighbour jumps {worst_jump} degrees");
    }

    /// An animated FBX comes back through our own reader with its time axis.
    #[test]
    fn the_animated_fbx_keeps_the_clips_time_axis() {
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes = super::export_fbx(
            &model("models/model-human.glb"),
            &skeleton,
            2.0,
            Some((&library(), "Chest_Open")),
        )
        .expect("exports");

        let path = std::env::temp_dir().join("m2m-animated.fbx");
        std::fs::write(&path, &bytes).expect("writes");
        println!("wrote {}", path.display());

        let scene = m2m_io::fbx::dom::Scene::from_document(
            m2m_io::fbx::binary::parse(&bytes).expect("our own reader reads it"),
        );
        // 30 fps, or every tick time is read at the wrong rate.
        assert_eq!(scene.time_mode, Some(6));

        let models = m2m_io::fbx::model::parse_all(&scene);
        let (clips, _) = m2m_io::fbx::animation::parse_all(&scene, &models);
        assert_eq!(clips.len(), 1);
        assert_eq!(clips[0].name, "Chest_Open");

        // The clip is 1.375 s. Counting keys proves nothing — the reader merges
        // axes onto one time array and can insert sub-keys — but the DURATION
        // is what plays.
        assert!(
            (clips[0].duration - 1.375).abs() < 0.01,
            "clip is {} s long",
            clips[0].duration
        );
        assert!(!clips[0].tracks.is_empty());

        // Translations must be in CENTIMETRES, like the rest of the FBX export.
        // In metres they are a hundred times too small, every key still reads
        // back, and the character barely moves — a silent failure that no
        // count or time-axis check sees.
        let travel = clips[0]
            .tracks
            .iter()
            .filter(|track| track.kind == m2m_io::fbx::animation::TrackKind::Position)
            .flat_map(|track| {
                let ys: Vec<f32> = track.values.chunks_exact(3).map(|v| v[1]).collect();
                let span = ys.iter().copied().fold(f32::MIN, f32::max)
                    - ys.iter().copied().fold(f32::MAX, f32::min);
                [span]
            })
            .fold(0.0f32, f32::max);
        assert!(
            travel > 1.0,
            "the largest vertical travel is {travel} file units, which is metres not centimetres"
        );
    }

    /// The overlay flags exactly the fallback vertices and colours the rest.
    #[test]
    fn weight_colors_flag_the_guessed_vertices_and_colour_the_rest() {
        use m2m_core::skinning::SkinWeights;

        // Three vertices: two solved, one fallback. Build the weights directly
        // so the fallback set is known, rather than depending on a real mesh
        // happening to have an island.
        let mut w = SkinWeights::zeroed(3);
        // vertex 0 dominated by bone 5, vertex 1 by bone 9.
        w.indices[0] = 5;
        w.weights[0] = 0.7;
        w.indices[1] = 2;
        w.weights[1] = 0.3;
        w.indices[4] = 9;
        w.weights[4] = 1.0;
        // vertex 2 is a fallback (bone 0, weight 1) AND listed as such.
        w.indices[8] = 0;
        w.weights[8] = 1.0;
        w.fallback_vertices.push(2);

        let colors = super::weight_colors(&w);
        assert_eq!(colors.len(), 3 * 4);

        // The flagged vertex is the flag red, opaque.
        assert_eq!(&colors[8..12], &[1.0, 0.15, 0.15, 1.0]);

        // The two solved vertices carry their DOMINANT bone's hue, and it
        // differs between bone 5 and bone 9 — a vertex on the wrong bone would
        // be a wrong colour.
        let hue5 = super::bone_hue(5);
        let hue9 = super::bone_hue(9);
        assert_ne!(hue5, hue9);
        assert_eq!(&colors[0..3], &hue5[..]);
        assert_eq!(&colors[4..7], &hue9[..]);
        // Not the flag colour, and opaque.
        assert_ne!(&colors[0..4], &[1.0, 0.15, 0.15, 1.0]);
        assert_eq!(colors[3], 1.0);
    }

    /// Bone hues are stable, in-gamut, and spread apart for neighbours.
    #[test]
    fn bone_hues_are_valid_and_neighbours_differ() {
        for bone in 0u16..66 {
            let [r, g, b] = super::bone_hue(bone);
            for c in [r, g, b] {
                assert!(
                    (0.0..=1.0).contains(&c),
                    "bone {bone} channel {c} out of gamut"
                );
            }
            // A fully-saturated hue always has one channel at 0 and one at 1.
            let max = r.max(g).max(b);
            let min = r.min(g).min(b);
            assert!(
                (max - 1.0).abs() < 1e-6 && min.abs() < 1e-6,
                "bone {bone} not full-sat"
            );
            // Adjacent bones are far apart on the wheel (golden angle ~222deg).
            let next = super::bone_hue(bone + 1);
            assert_ne!(
                [r, g, b],
                next,
                "bone {bone} shares a hue with its neighbour"
            );
        }
    }

    /// The overlay is a rigged glb whose vertices carry colours.
    #[test]
    fn the_overlay_bakes_colours_into_the_mesh() {
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes =
            super::overlay_glb(&model("models/model-human.glb"), &skeleton, 2.0).expect("overlays");

        // The colours travel in the file's JSON as a COLOR_0 accessor — our own
        // reader does not surface them, so assert against the JSON chunk that
        // the viewer's loader will read.
        let json_len = u32::from_le_bytes(bytes[12..16].try_into().unwrap()) as usize;
        let json: serde_json::Value =
            serde_json::from_slice(&bytes[20..20 + json_len]).expect("json chunk");
        let attrs = &json["meshes"][0]["primitives"][0]["attributes"];
        assert!(
            attrs.get("COLOR_0").is_some(),
            "no COLOR_0 attribute written"
        );

        // And it is still a valid rigged model our own reader accepts.
        let back = m2m_io::glb::read(&bytes).expect("reads back");
        assert_eq!(back.skins.len(), 1);
        assert!(back.nodes.iter().any(|n| n.name == "pelvis"));
    }

    /// The Euler order we write is the one the reader reads back.
    #[test]
    fn an_fbx_euler_round_trip_recovers_the_quaternion() {
        // FBX carries `Lcl Rotation` as Euler degrees, so a quaternion has to
        // be decomposed to write it. The order matters and the names mislead:
        // `fbx::transform` composes `Rz * Ry * Rx` for its default order, which
        // is EXTRINSIC XYZ, not the intrinsic XYZ of the same name. Getting it
        // wrong is not a rounding error — it put every cluster 82 cm away.
        for quaternion in [
            glam::Quat::from_rotation_x(0.7),
            glam::Quat::from_rotation_y(-1.2),
            glam::Quat::from_euler(glam::EulerRot::XYZEx, 0.3, -0.9, 2.1),
        ] {
            let (x, y, z) = quaternion.to_euler(glam::EulerRot::XYZEx);
            // Rebuilt the way `fbx::transform::euler_matrix` does it.
            let rebuilt = glam::Mat4::from_rotation_z(z)
                * glam::Mat4::from_rotation_y(y)
                * glam::Mat4::from_rotation_x(x);
            let expected = glam::Mat4::from_quat(quaternion);
            for (a, b) in rebuilt
                .to_cols_array()
                .iter()
                .zip(expected.to_cols_array().iter())
            {
                assert!((a - b).abs() < 1e-5, "{rebuilt:?} is not {expected:?}");
            }
        }
    }

    /// The bind pose the clusters record is the pose the skeleton is in.
    #[test]
    fn every_cluster_binds_to_where_its_bone_actually_is() {
        // FBX binds with a PAIR of global matrices, and `TransformLink` is the
        // bone's world at bind. Getting it wrong — the identity, say — leaves
        // every count correct and every vertex bound as though its bone sat at
        // the origin, so the mesh tears apart the moment it is posed. Neither
        // Blender's report nor assimp's would say a word.
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes = super::export_fbx(&model("models/model-human.glb"), &skeleton, 2.0, None)
            .expect("exports");

        let scene = m2m_io::fbx::dom::Scene::from_document(
            m2m_io::fbx::binary::parse(&bytes).expect("reads"),
        );
        let models = m2m_io::fbx::model::parse_all(&scene);
        let (skins, _) = m2m_io::fbx::skin::parse_all(&scene);

        let mut worst = 0.0f64;
        for cluster in &skins[0].clusters {
            let bone = models.get(cluster.bone_id).expect("the cluster's bone");
            for (a, b) in bone
                .world
                .to_cols_array()
                .iter()
                .zip(cluster.transform_link.to_cols_array().iter())
            {
                worst = worst.max((a - b).abs());
            }
        }
        // Measured 5.0e-5 file units — half a micrometre on a 180 cm
        // character. `Lcl Rotation` is stored as Euler DEGREES, so an f32
        // quaternion is decomposed and recomposed to get here; the tolerance
        // is that round trip, not slack. It was 1e-6 while `transform_link`
        // was a bare translation and exact.
        assert!(
            worst < 1e-3,
            "a cluster binds {worst} file units away from where its bone stands"
        );
        assert!(!skins[0].clusters.is_empty());
    }

    /// Every solved influence reaches a cluster, and no bone gets an empty one.
    #[test]
    fn the_fbx_clusters_carry_every_influence_exactly_once() {
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes = super::export_fbx(&model("models/model-human.glb"), &skeleton, 2.0, None)
            .expect("exports");

        let scene = m2m_io::fbx::dom::Scene::from_document(
            m2m_io::fbx::binary::parse(&bytes).expect("reads"),
        );
        let (skins, _) = m2m_io::fbx::skin::parse_all(&scene);
        assert_eq!(skins.len(), 1);

        // The report and the file are computed by different code from the same
        // solve, so agreeing is worth something.
        let report = super::bind(&model("models/model-human.glb"), &skeleton, 2.0).expect("binds");
        let influences: usize = skins[0].clusters.iter().map(|c| c.indices.len()).sum();
        let expected: usize = report
            .influence_histogram
            .iter()
            .enumerate()
            .map(|(slot, count)| (slot + 1) * count)
            .sum();
        assert_eq!(
            influences, expected,
            "an influence was dropped or duplicated"
        );

        // A bone that influences nothing gets no cluster, not an empty one.
        assert!(skins[0].clusters.iter().all(|c| !c.indices.is_empty()));
        assert!(skins[0].clusters.len() <= report.weighted_bones);

        // Every weight is a real share, and the parallel arrays line up.
        for cluster in &skins[0].clusters {
            assert_eq!(cluster.indices.len(), cluster.weights.len());
            assert!(cluster.weights.iter().all(|w| *w > 0.0 && *w <= 1.0));
        }
    }

    /// A skeleton whose parent comes after its child is refused, not panicked on.
    #[test]
    fn a_bone_ordered_after_its_parent_is_refused() {
        // `fbx::build` panics on this rather than returning an error, and a
        // FittedSkeleton comes in from the frontend.
        let skeleton = super::FittedSkeleton {
            bones: vec!["child".into(), "parent".into()],
            parents: vec![Some(1), None],
            positions: vec![[0.0, 1.0, 0.0], [0.0, 0.0, 0.0]],
            rotations: vec![[0.0, 0.0, 0.0, 1.0], [0.0, 0.0, 0.0, 1.0]],
            scale: 1.0,
            pose: "other".into(),
        };
        let err = super::export_fbx(&model("models/model-human.glb"), &skeleton, 2.0, None)
            .expect_err("refused");

        assert!(
            matches!(err, super::RigError::BadBoneOrder { bone: 0, parent: 1 }),
            "got {err:?}"
        );
    }

    #[test]
    fn a_template_nobody_ships_is_refused_by_name() {
        let err = fit("chimera", &model("models/model-human.glb")).expect_err("refused");
        assert!(
            matches!(err, super::RigError::UnknownTemplate(name) if name == "chimera"),
            "wrong error"
        );
    }

    #[test]
    fn a_file_that_is_not_a_model_is_refused_rather_than_fitted() {
        let err = fit("human", b"\x89PNG\r\n\x1a\n not a model").expect_err("refused");
        assert!(matches!(err, super::RigError::Import(_)), "got {err:?}");
    }
}
