//! Choosing a skeleton and placing it on the imported mesh.
//!
//! # Boundary
//!
//! This is projection, not algorithm (`memory/architecture.md` §2). The fitting
//! lives in `m2m_rig::fit`; what happens here is turning a `glb::Document` into
//! the plain inputs that crate takes. `m2m-rig` deliberately does **not** depend
//! on `m2m-io` — the rigging maths has no business knowing about file formats —
//! so somebody has to bridge the two, and the adapter is the right somebody.

use m2m_rig::fit::{Fitted, RestPose};
use serde::Serialize;

// Generated by `build.rs`: every rig `.glb`, by file name.
include!(concat!(env!("OUT_DIR"), "/skeletons.rs"));

/// A creature template offered in the Choose Skeleton step.
#[derive(Debug, Serialize)]
pub struct SkeletonTemplate {
    /// The template's name, e.g. `human`.
    pub name: String,
    /// How many bones its skeleton has.
    pub bones: usize,
    /// Chain names, so the UI can say what the rig actually covers.
    pub chains: Vec<String>,
    /// Whether the rig for it is available to fit.
    ///
    /// A manifest naming a `.glb` that is not embedded would otherwise fail
    /// only when the user picked it.
    pub available: bool,
}

/// A template skeleton placed on a mesh, ready to draw.
#[derive(Debug, Serialize, PartialEq)]
pub struct FittedSkeleton {
    /// Bone names.
    pub bones: Vec<String>,
    /// Each bone's parent, as an index into `bones`. `None` for a root.
    ///
    /// Carried because a skeleton is drawn as segments between a bone and its
    /// parent, and [`Fitted`] is only names and positions — the hierarchy lives
    /// in the rig file's node graph.
    pub parents: Vec<Option<usize>>,
    /// World-space position of each bone, in metres.
    pub positions: Vec<[f32; 3]>,
    /// The uniform scale the template was fitted with, reported so a wildly
    /// wrong pick is visible as a number and not only as a shape.
    pub scale: f32,
}

/// Errors the skeleton step can produce.
#[derive(Debug, thiserror::Error)]
pub enum RigError {
    /// The shipped manifests did not parse.
    #[error("template manifests: {0}")]
    Manifests(#[from] serde_json::Error),
    /// No template by that name ships.
    #[error("no template named {0}")]
    UnknownTemplate(String),
    /// The template names a rig file that is not embedded.
    #[error("template {template} needs {skeleton}, which is not bundled")]
    MissingSkeleton {
        /// The template that asked.
        template: String,
        /// The file it named.
        skeleton: String,
    },
    /// A rig file could not be read.
    #[error(transparent)]
    Read(#[from] m2m_io::glb::GlbError),
    /// The model the user imported could not be read.
    #[error(transparent)]
    Import(#[from] m2m_io::import::ImportError),
    /// The rig carries no skin, so there is no joint list to fit.
    #[error("{0} has no skin, so it names no bones")]
    NoSkin(String),
    /// The fitting pipeline could not place the skeleton.
    #[error("cannot fit {template}: the mesh or the template has nothing to work with")]
    CannotFit {
        /// The template that was being fitted.
        template: String,
    },
}

/// Every template that ships, with whether its rig is actually bundled.
pub fn templates() -> Result<Vec<SkeletonTemplate>, RigError> {
    Ok(m2m_rig::template::all()?
        .into_iter()
        .map(|template| SkeletonTemplate {
            bones: template.bones().count(),
            chains: template.chains.iter().map(|c| c.name.clone()).collect(),
            available: skeleton_bytes(&template.skeleton).is_some(),
            name: template.name,
        })
        .collect())
}

/// The bytes of an embedded rig, by the file name a manifest gives.
fn skeleton_bytes(name: &str) -> Option<&'static [u8]> {
    SKELETONS
        .iter()
        .find(|(embedded, _)| *embedded == name)
        .map(|(_, bytes)| *bytes)
}

/// Places a named template's skeleton on a model.
///
/// # Errors
///
/// [`RigError`] for an unknown template, a rig that is not bundled, a file that
/// will not read, or a mesh the pipeline cannot place a skeleton on.
pub fn fit(template_name: &str, model: &[u8]) -> Result<FittedSkeleton, RigError> {
    let template = m2m_rig::template::all()?
        .into_iter()
        .find(|t| t.name == template_name)
        .ok_or_else(|| RigError::UnknownTemplate(template_name.to_owned()))?;

    let rig_bytes =
        skeleton_bytes(&template.skeleton).ok_or_else(|| RigError::MissingSkeleton {
            template: template.name.clone(),
            skeleton: template.skeleton.clone(),
        })?;

    let rig = m2m_io::glb::read(rig_bytes)?;
    let (rest, parents) = rest_pose(&rig, &template.skeleton)?;
    let mesh = mesh_of(&m2m_io::import::load(model)?);

    // 128 is the resolution the fitting tests use across all nine creatures.
    let fitted: Fitted =
        m2m_rig::fit::fit_template(&template, &rest, &mesh, 128).ok_or(RigError::CannotFit {
            template: template.name.clone(),
        })?;

    Ok(FittedSkeleton {
        parents,
        positions: fitted.positions.iter().map(|p| p.to_array()).collect(),
        scale: fitted.scale,
        bones: fitted.bones,
    })
}

/// A rig's joints as a rest pose, plus each joint's parent within the joint list.
///
/// A joint's parent is its parent **node**, looked up in the joint list. That
/// is only correct while no rig puts a plain node in the middle of a bone
/// chain, and all nine shipped rigs satisfy it — measured: the direct-parent
/// rule and a full nearest-joint-ancestor walk agree on every joint of every
/// rig, and each has exactly one root. The walk was written first and removed
/// once the measurement showed it was untested defensive code;
/// `every_rig_hangs_its_bones_directly_off_each_other` is what fails if a
/// future asset breaks the assumption.
fn rest_pose(
    document: &m2m_io::glb::Document,
    name: &str,
) -> Result<(RestPose, Vec<Option<usize>>), RigError> {
    let skin = document
        .skins
        .first()
        .ok_or_else(|| RigError::NoSkin(name.to_owned()))?;
    let world = document.world_transforms();

    let mut joint_of = vec![None; document.nodes.len()];
    for (slot, &node) in skin.joints.iter().enumerate() {
        if let Some(entry) = joint_of.get_mut(node) {
            *entry = Some(slot);
        }
    }

    let parents = skin
        .joints
        .iter()
        .map(|&node| {
            let parent = document.nodes.get(node)?.parent?;
            joint_of.get(parent).copied().flatten()
        })
        .collect();

    let rest = RestPose {
        bones: skin
            .joints
            .iter()
            .filter_map(|&j| document.nodes.get(j).map(|n| n.name.clone()))
            .collect(),
        positions: skin
            .joints
            .iter()
            .filter_map(|&j| world.get(j).map(|m| m.transform_point3(glam::Vec3::ZERO)))
            .collect(),
    };
    Ok((rest, parents))
}

/// A document's geometry as one mesh in world space.
fn mesh_of(document: &m2m_io::glb::Document) -> m2m_core::mesh::Mesh {
    let world = document.world_transforms();
    let mut mesh = m2m_core::mesh::Mesh::default();
    for primitive in &document.primitives {
        let transform = primitive
            .node
            .and_then(|n| world.get(n).copied())
            .unwrap_or(glam::Mat4::IDENTITY);
        let base = mesh.positions.len() as u32;
        for chunk in primitive.positions.chunks_exact(3) {
            mesh.positions
                .push(transform.transform_point3(glam::Vec3::new(chunk[0], chunk[1], chunk[2])));
        }
        mesh.indices
            .extend(primitive.indices.iter().map(|i| i + base));
    }
    mesh
}

#[cfg(test)]
mod tests {
    use super::{fit, templates};

    fn model(relative: &str) -> Vec<u8> {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../legacy/static/").to_owned() + relative;
        std::fs::read(&path).unwrap_or_else(|e| panic!("reading {path}: {e}"))
    }

    #[test]
    fn every_shipped_template_has_the_rig_it_names() {
        // A manifest naming a `.glb` that is not embedded would fail only when
        // a user picked that creature, which is the worst time to find out.
        let offered = templates().expect("the shipped manifests parse");

        assert_eq!(offered.len(), 9);
        for template in &offered {
            assert!(template.available, "{} has no bundled rig", template.name);
            assert!(template.bones > 0, "{} claims no bones", template.name);
            assert!(
                !template.chains.is_empty(),
                "{} has no chains",
                template.name
            );
        }
        assert_eq!(offered.iter().map(|t| t.bones).sum::<usize>(), 500);
    }

    #[test]
    fn fitting_places_the_human_rig_on_a_human_mesh() {
        let fitted = fit("human", &model("models/model-human.glb")).expect("fits");

        assert_eq!(fitted.bones.len(), 66);
        assert_eq!(fitted.positions.len(), 66);
        assert_eq!(fitted.parents.len(), 66);
        assert!(fitted.bones.contains(&"pelvis".to_owned()));

        // The model is 1.83 m tall and the rig was authored at the same scale,
        // so a fit that had to scale by 10 would mean the units were wrong.
        assert!(
            (0.5..2.0).contains(&fitted.scale),
            "scale {} is not plausible",
            fitted.scale
        );
    }

    #[test]
    fn exactly_one_bone_is_a_root_and_every_other_parent_is_real() {
        // A skeleton is drawn as segments from each bone to its parent, so a
        // parent index that is out of range, or a second root, is a hole in
        // the drawing rather than an error anyone would see.
        let fitted = fit("human", &model("models/model-human.glb")).expect("fits");

        let roots = fitted.parents.iter().filter(|p| p.is_none()).count();
        assert_eq!(roots, 1, "expected one root, got {roots}");
        for (index, parent) in fitted.parents.iter().enumerate() {
            let Some(parent) = *parent else { continue };
            assert!(
                parent < fitted.bones.len(),
                "bone {index} has no such parent"
            );
            assert_ne!(parent, index, "bone {index} is its own parent");
        }
    }

    /// Every shipped rig hangs each bone directly off another bone.
    #[test]
    fn every_rig_hangs_its_bones_directly_off_each_other() {
        // What `rest_pose`'s parent lookup assumes. A rig with a plain node in
        // the middle of a chain would silently produce a second root and a
        // skeleton drawn with a hole in it, so the assumption is asserted
        // rather than trusted.
        for template in templates().expect("manifests parse") {
            let fitted = fit(&template.name, &model("models/model-human.glb"));
            // Fitting a human mesh with a shark rig is allowed to fail; the
            // parent structure is what is under test, so read it directly.
            let Ok(fitted) = fitted else { continue };
            assert_eq!(
                fitted.parents.iter().filter(|p| p.is_none()).count(),
                1,
                "{} does not have exactly one root",
                template.name
            );
        }
    }

    #[test]
    fn a_template_nobody_ships_is_refused_by_name() {
        let err = fit("chimera", &model("models/model-human.glb")).expect_err("refused");
        assert!(
            matches!(err, super::RigError::UnknownTemplate(name) if name == "chimera"),
            "wrong error"
        );
    }

    #[test]
    fn a_file_that_is_not_a_model_is_refused_rather_than_fitted() {
        let err = fit("human", b"\x89PNG\r\n\x1a\n not a model").expect_err("refused");
        assert!(matches!(err, super::RigError::Import(_)), "got {err:?}");
    }
}
