//! Choosing a skeleton and placing it on the imported mesh.
//!
//! # Boundary
//!
//! This is projection, not algorithm (`memory/architecture.md` §2). The fitting
//! lives in `m2m_rig::fit`; what happens here is turning a `glb::Document` into
//! the plain inputs that crate takes. `m2m-rig` deliberately does **not** depend
//! on `m2m-io` — the rigging maths has no business knowing about file formats —
//! so somebody has to bridge the two, and the adapter is the right somebody.

use m2m_rig::fit::{Fitted, RestPose};
use serde::{Deserialize, Serialize};

// Generated by `build.rs`: every rig `.glb`, by file name.
include!(concat!(env!("OUT_DIR"), "/skeletons.rs"));

/// A creature template offered in the Choose Skeleton step.
#[derive(Debug, Serialize)]
pub struct SkeletonTemplate {
    /// The template's name, e.g. `human`.
    pub name: String,
    /// How many bones its skeleton has.
    pub bones: usize,
    /// Chain names, so the UI can say what the rig actually covers.
    pub chains: Vec<String>,
    /// Whether the rig for it is available to fit.
    ///
    /// A manifest naming a `.glb` that is not embedded would otherwise fail
    /// only when the user picked it.
    pub available: bool,
}

/// A template skeleton placed on a mesh, ready to draw.
///
/// Deserialisable as well as serialisable: it goes out to the frontend to be
/// drawn and comes back to be bound, which is what will let a user's manual
/// adjustments reach the solver once the gizmo exists.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct FittedSkeleton {
    /// Bone names.
    pub bones: Vec<String>,
    /// Each bone's parent, as an index into `bones`. `None` for a root.
    ///
    /// Carried because a skeleton is drawn as segments between a bone and its
    /// parent, and [`Fitted`] is only names and positions — the hierarchy lives
    /// in the rig file's node graph.
    pub parents: Vec<Option<usize>>,
    /// World-space position of each bone, in metres.
    pub positions: Vec<[f32; 3]>,
    /// The uniform scale the template was fitted with, reported so a wildly
    /// wrong pick is visible as a number and not only as a shape.
    pub scale: f32,
}

/// Errors the skeleton step can produce.
#[derive(Debug, thiserror::Error)]
pub enum RigError {
    /// The shipped manifests did not parse.
    #[error("template manifests: {0}")]
    Manifests(#[from] serde_json::Error),
    /// No template by that name ships.
    #[error("no template named {0}")]
    UnknownTemplate(String),
    /// The template names a rig file that is not embedded.
    #[error("template {template} needs {skeleton}, which is not bundled")]
    MissingSkeleton {
        /// The template that asked.
        template: String,
        /// The file it named.
        skeleton: String,
    },
    /// A rig file could not be read.
    #[error(transparent)]
    Read(#[from] m2m_io::glb::GlbError),
    /// The model the user imported could not be read.
    #[error(transparent)]
    Import(#[from] m2m_io::import::ImportError),
    /// The rig carries no skin, so there is no joint list to fit.
    #[error("{0} has no skin, so it names no bones")]
    NoSkin(String),
    /// There was nothing to bind, or nothing to bind it to.
    #[error("cannot bind: {reason}")]
    NothingToBind {
        /// What was missing.
        reason: &'static str,
    },
    /// A bone's parent appears after it, which `fbx::build` cannot express.
    #[error("bone {bone} has parent {parent}, which comes after it")]
    BadBoneOrder {
        /// The bone whose parent is out of order.
        bone: usize,
        /// The parent that comes too late.
        parent: usize,
    },
    /// Writing the FBX failed.
    #[error(transparent)]
    Fbx(#[from] m2m_io::fbx::FbxError),
    /// The fitting pipeline could not place the skeleton.
    #[error("cannot fit {template}: the mesh or the template has nothing to work with")]
    CannotFit {
        /// The template that was being fitted.
        template: String,
    },
}

/// Every template that ships, with whether its rig is actually bundled.
pub fn templates() -> Result<Vec<SkeletonTemplate>, RigError> {
    Ok(m2m_rig::template::all()?
        .into_iter()
        .map(|template| SkeletonTemplate {
            bones: template.bones().count(),
            chains: template.chains.iter().map(|c| c.name.clone()).collect(),
            available: skeleton_bytes(&template.skeleton).is_some(),
            name: template.name,
        })
        .collect())
}

/// The bytes of an embedded rig, by the file name a manifest gives.
fn skeleton_bytes(name: &str) -> Option<&'static [u8]> {
    SKELETONS
        .iter()
        .find(|(embedded, _)| *embedded == name)
        .map(|(_, bytes)| *bytes)
}

/// Places a named template's skeleton on a model.
///
/// # Errors
///
/// [`RigError`] for an unknown template, a rig that is not bundled, a file that
/// will not read, or a mesh the pipeline cannot place a skeleton on.
pub fn fit(template_name: &str, model: &[u8]) -> Result<FittedSkeleton, RigError> {
    let template = m2m_rig::template::all()?
        .into_iter()
        .find(|t| t.name == template_name)
        .ok_or_else(|| RigError::UnknownTemplate(template_name.to_owned()))?;

    let rig_bytes =
        skeleton_bytes(&template.skeleton).ok_or_else(|| RigError::MissingSkeleton {
            template: template.name.clone(),
            skeleton: template.skeleton.clone(),
        })?;

    let rig = m2m_io::glb::read(rig_bytes)?;
    let (rest, parents) = rest_pose(&rig, &template.skeleton)?;
    let mesh = mesh_of(&m2m_io::import::load(model)?);

    // 128 is the resolution the fitting tests use across all nine creatures.
    let fitted: Fitted =
        m2m_rig::fit::fit_template(&template, &rest, &mesh, 128).ok_or(RigError::CannotFit {
            template: template.name.clone(),
        })?;

    Ok(FittedSkeleton {
        parents,
        positions: fitted.positions.iter().map(|p| p.to_array()).collect(),
        scale: fitted.scale,
        bones: fitted.bones,
    })
}

/// What binding produced, without the weights themselves.
///
/// The weights are `vertices x 4` indices and `vertices x 4` floats — about
/// 600 KB for the reference character — so they belong on the bulk channel
/// beside the geometry, not in a JSON reply. Until something draws them, what
/// crosses is the part a person can act on: whether every vertex is attached,
/// and where the solver had to guess.
#[derive(Debug, Serialize, PartialEq)]
pub struct BindReport {
    /// Vertices in the mesh that was bound.
    pub vertices: usize,
    /// Bones allowed to receive weight.
    pub weighted_bones: usize,
    /// Bones excluded because they are the root or a leaf.
    pub excluded_bones: usize,
    /// Vertices no bone reached through the mesh, which fell back to the
    /// nearest bone in a straight line.
    ///
    /// Non-zero means part of the model is a disconnected island — a loose
    /// accessory, or a limb modelled apart from the body. Reported because the
    /// deformation there is a guess, and a guess the user can see is one they
    /// can fix.
    pub fallback_vertices: usize,
    /// How many vertices have 1, 2, 3 or 4 influences.
    pub influence_histogram: [usize; 4],
    /// Vertices with no influence at all.
    ///
    /// Counted separately rather than folded into the histogram's first bucket:
    /// an unweighted vertex is not a lightly-weighted one, it is a vertex that
    /// detaches when the rig moves, and the two must never look alike.
    ///
    /// **This is a canary across a crate boundary, and no test can make it
    /// fire.** `m2m_core::skinning::assign_weights` always writes at least one
    /// influence — a vertex no bone reached takes the straight-line fallback at
    /// weight 1.0 — so nothing that can be fed in produces a non-zero here. A
    /// mutation folding this back into the histogram therefore survives, by
    /// construction rather than for want of a fixture. It stays because the
    /// invariant belongs to another crate and this costs one counter.
    pub unweighted_vertices: usize,
}

/// Binds a mesh to a fitted skeleton.
///
/// # Bone segments
///
/// A bone runs from its own joint **towards its first child**, which is what
/// "the bone" means to anyone looking at it: vertices near the upper arm should
/// follow `upperarm`. The tempting alternative — a segment from the parent's
/// joint down to this one — is off by one, and would weight the shoulder to the
/// upper arm. A branching joint such as the hips has no single continuation and
/// takes its first child in joint order; a leaf bone's segment is a point,
/// which costs nothing because leaves are excluded from weighting anyway.
///
/// # The bone mask
///
/// The root and every leaf are excluded, which is the legacy invariant
/// `m2m_core::skinning::BoneMask` documents: the root carries global transform
/// only, and a leaf exists to orient its parent.
///
/// # Errors
///
/// [`RigError`] for a model that will not read, a mesh that cannot be
/// voxelised, or a skeleton with nothing that may hold weight.
pub fn bind(model: &[u8], skeleton: &FittedSkeleton, falloff: f32) -> Result<BindReport, RigError> {
    Ok(solve(model, skeleton, falloff)?.2)
}

/// The solve behind [`bind`] and [`export_glb`]: mesh, weights and report.
///
/// Export recomputes rather than carrying the weights out to the frontend and
/// back — they are about 600 KB, and the whole solve takes ~56 ms on the
/// reference body. A round trip through the webview would cost more than doing
/// it twice, and there would be a cache to invalidate every time a bone moved.
fn solve(
    model: &[u8],
    skeleton: &FittedSkeleton,
    falloff: f32,
) -> Result<
    (
        m2m_core::mesh::Mesh,
        m2m_core::skinning::SkinWeights,
        BindReport,
    ),
    RigError,
> {
    let mesh = mesh_of(&m2m_io::import::load(model)?);
    if mesh.positions.is_empty() {
        return Err(RigError::NothingToBind {
            reason: "the model has no vertices",
        });
    }

    let mut has_child = vec![false; skeleton.bones.len()];
    for parent in skeleton.parents.iter().flatten() {
        if let Some(slot) = has_child.get_mut(*parent) {
            *slot = true;
        }
    }

    let segments = bone_segments(skeleton);

    // A bone that is neither the root nor a leaf may hold weight.
    let allowed: Vec<bool> = (0..skeleton.bones.len())
        .map(|bone| skeleton.parents.get(bone).copied().flatten().is_some() && has_child[bone])
        .collect();
    let weighted_bones = allowed.iter().filter(|a| **a).count();
    if weighted_bones == 0 {
        return Err(RigError::NothingToBind {
            reason: "every bone is either the root or a leaf",
        });
    }

    let grid = m2m_core::voxel::VoxelGrid::build(&mesh, 128).ok_or(RigError::NothingToBind {
        reason: "the mesh could not be voxelised",
    })?;
    let field = m2m_core::geodesic::GeodesicField::compute(&mesh, &grid, &segments).ok_or(
        RigError::NothingToBind {
            reason: "no bone could reach the mesh",
        },
    )?;

    let weights = m2m_core::skinning::assign_weights(
        &field,
        &mesh.positions,
        &segments,
        &allowed,
        m2m_core::skinning::SkinningParams::new(falloff),
    );

    let mut influence_histogram = [0usize; 4];
    let mut unweighted_vertices = 0usize;
    for vertex in 0..weights.vertex_count() {
        match weights.influences(vertex).count() {
            0 => unweighted_vertices += 1,
            count => {
                if let Some(slot) = influence_histogram.get_mut(count - 1) {
                    *slot += 1;
                }
            }
        }
    }

    let report = BindReport {
        vertices: mesh.positions.len(),
        weighted_bones,
        excluded_bones: skeleton.bones.len() - weighted_bones,
        fallback_vertices: weights.fallback_vertices.len(),
        influence_histogram,
        unweighted_vertices,
    };
    Ok((mesh, weights, report))
}

/// Writes the rigged model as a `.glb`: mesh, skeleton and skin weights.
///
/// # What the exported file is
///
/// The mesh in world space, one node per bone at its fitted position, and a
/// skin binding them. Bone rotations are identity: a fitted skeleton is a set
/// of joint **positions**, and inventing orientations for it would be making up
/// data the fitter never produced. A joint's position is what deforms the mesh,
/// so the export is complete for skinning even though a bone roll is not
/// recovered.
///
/// Inverse bind matrices are the inverse of each bone's world translation,
/// which is exact here because the mesh node carries the identity: the mesh
/// positions are already in world space, so `jointWorld * IBM` is the identity
/// at bind and the mesh does not move until a bone does.
///
/// # Errors
///
/// Whatever the solve produces, plus a write failure from `glb::write`.
pub fn export_glb(
    model: &[u8],
    skeleton: &FittedSkeleton,
    falloff: f32,
) -> Result<Vec<u8>, RigError> {
    let (mesh, weights, _) = solve(model, skeleton, falloff)?;

    let position = |index: usize| {
        skeleton
            .positions
            .get(index)
            .map_or(glam::Vec3::ZERO, |p| glam::Vec3::from(*p))
    };

    // One node per bone. A bone's local translation is its offset from its
    // parent, so the composed world lands back on the fitted position.
    let mut nodes: Vec<m2m_io::glb::Node> = skeleton
        .bones
        .iter()
        .enumerate()
        .map(|(bone, name)| {
            let parent = skeleton.parents.get(bone).copied().flatten();
            let local = position(bone) - parent.map_or(glam::Vec3::ZERO, position);
            m2m_io::glb::Node {
                name: name.clone(),
                parent,
                transform: m2m_io::glb::Trs {
                    translation: local.to_array(),
                    rotation: [0.0, 0.0, 0.0, 1.0],
                    scale: [1.0, 1.0, 1.0],
                },
                skin: None,
            }
        })
        .collect();

    let inverse_bind_matrices = (0..skeleton.bones.len())
        .map(|bone| {
            glam::Mat4::from_translation(position(bone))
                .inverse()
                .to_cols_array()
        })
        .collect();

    // The mesh hangs off its own node, which carries the skin. glTF ignores a
    // skinned node's transform, so the identity here is not a simplification.
    let mesh_node = nodes.len();
    nodes.push(m2m_io::glb::Node {
        name: "mesh".into(),
        parent: None,
        transform: m2m_io::glb::Trs {
            translation: [0.0, 0.0, 0.0],
            rotation: [0.0, 0.0, 0.0, 1.0],
            scale: [1.0, 1.0, 1.0],
        },
        skin: Some(0),
    });

    let document = m2m_io::glb::Document {
        primitives: vec![m2m_io::glb::Primitive {
            mesh: 0,
            node: Some(mesh_node),
            positions: mesh.positions.iter().flat_map(|p| p.to_array()).collect(),
            indices: mesh.indices.clone(),
            joints: weights.indices.clone(),
            weights: weights.weights.clone(),
        }],
        skins: vec![m2m_io::glb::Skin {
            joints: (0..skeleton.bones.len()).collect(),
            inverse_bind_matrices,
        }],
        nodes,
        clips: Vec::new(),
        report: m2m_io::glb::GlbReport::default(),
    };

    Ok(m2m_io::glb::write(&document)?)
}

/// Centimetres per metre. Our meshes are in metres, the glTF convention;
/// `fbx::build` writes `UnitScaleFactor` 1.0, which declares centimetres. Metre
/// values in a file that says centimetres import as a 1.8 cm character.
const CM_PER_M: f64 = 100.0;

/// Writes the rigged model as a binary `.fbx`.
///
/// # Why a second writer rather than a conversion
///
/// FBX is not glTF with different bytes. It counts in the unit its
/// `GlobalSettings` declare, it binds skins with a pair of global matrices
/// rather than one inverse, and it names bones on `Model`/`LimbNode` objects.
/// `m2m_io::fbx::build` already speaks all of that and is verified against
/// Blender; what is missing is the shape of our data in its terms.
///
/// # Two things this must get right
///
/// **Units.** Positions and bone offsets are multiplied by
/// [`CM_PER_M`], because the builder declares centimetres.
///
/// **Cluster inversion.** Weights arrive per vertex, four slots each; FBX wants
/// them per bone, as parallel index and weight lists. A bone that ended up
/// influencing nothing gets no cluster at all rather than an empty one.
///
/// # Errors
///
/// Whatever the solve produces, plus [`RigError::BadBoneOrder`] — `build`
/// *panics* on a parent that appears after its child, and a `FittedSkeleton`
/// arrives from the frontend, so the order is checked here rather than trusted.
pub fn export_fbx(
    model: &[u8],
    skeleton: &FittedSkeleton,
    falloff: f32,
) -> Result<Vec<u8>, RigError> {
    use m2m_io::fbx::build;

    for (bone, parent) in skeleton.parents.iter().enumerate() {
        if let Some(parent) = *parent {
            if parent >= bone {
                return Err(RigError::BadBoneOrder { bone, parent });
            }
        }
    }

    let (mesh, weights, _) = solve(model, skeleton, falloff)?;

    let position = |index: usize| {
        skeleton
            .positions
            .get(index)
            .map_or(glam::DVec3::ZERO, |p| {
                glam::DVec3::new(p[0] as f64, p[1] as f64, p[2] as f64) * CM_PER_M
            })
    };

    let bones: Vec<build::Bone> = skeleton
        .bones
        .iter()
        .enumerate()
        .map(|(bone, name)| {
            let parent = skeleton.parents.get(bone).copied().flatten();
            let local = position(bone) - parent.map_or(glam::DVec3::ZERO, position);
            build::Bone {
                name,
                parent,
                translation: local.to_array(),
                // The fitter produces joint POSITIONS, not orientations, so
                // there is nothing truthful to put here — see `export_glb`.
                rotation: [0.0; 3],
                scale: [1.0; 3],
                pre_rotation: [0.0; 3],
            }
        })
        .collect();

    let positions: Vec<f32> = mesh
        .positions
        .iter()
        .flat_map(|p| (*p * CM_PER_M as f32).to_array())
        .collect();
    let meshes = [build::Mesh {
        name: "mesh",
        positions: &positions,
        faces: build::Faces::Triangles(&mesh.indices),
    }];

    // Weights come per vertex with four slots; FBX wants them per bone.
    let mut vertices_of: Vec<Vec<u32>> = vec![Vec::new(); skeleton.bones.len()];
    let mut weights_of: Vec<Vec<f64>> = vec![Vec::new(); skeleton.bones.len()];
    for vertex in 0..weights.vertex_count() {
        for (bone, weight) in weights.influences(vertex) {
            let Some(slot) = vertices_of.get_mut(bone as usize) else {
                continue;
            };
            slot.push(vertex as u32);
            weights_of[bone as usize].push(f64::from(weight));
        }
    }

    // The mesh's global transform at bind is the identity: its positions are
    // already where they sit, so a cluster's `transform` carries nothing.
    let identity = glam::DMat4::IDENTITY.to_cols_array();
    let clusters: Vec<build::Cluster> = (0..skeleton.bones.len())
        .filter(|bone| !vertices_of[*bone].is_empty())
        .map(|bone| build::Cluster {
            bone,
            indices: &vertices_of[bone],
            weights: &weights_of[bone],
            transform: identity,
            transform_link: glam::DMat4::from_translation(position(bone)).to_cols_array(),
        })
        .collect();
    let skins = [build::Skin {
        mesh: 0,
        clusters: &clusters,
    }];

    let scene = build::Scene {
        meshes: &meshes,
        bones: &bones,
        skins: &skins,
        clips: &[],
        // 30fps. Nothing here is animated, but the field is not optional and a
        // wrong frame rate would misread any clip added later.
        time_mode: 6,
    };

    Ok(m2m_io::fbx::encode::encode(&build::build(&scene))?)
}

/// Each bone as a segment the solver can measure distance to.
///
/// A bone runs from its own joint **towards its first child**. That is what
/// "the bone" means to anyone looking at it: vertices near the upper arm should
/// follow `upperarm`. The tempting alternative — a segment from the parent's
/// joint down to this one — is off by one, and would weight the shoulder to the
/// upper arm.
///
/// A branching joint such as the hips has no single continuation and takes its
/// first child in joint order; that is a judgement call, and the alternatives
/// (a point at the joint, or the average of the children) lose the torso's
/// reach. A leaf's segment is a point, which costs nothing because leaves never
/// hold weight.
fn bone_segments(skeleton: &FittedSkeleton) -> Vec<m2m_core::geodesic::BoneSegment> {
    let position = |index: usize| {
        skeleton
            .positions
            .get(index)
            .map_or(glam::Vec3::ZERO, |p| glam::Vec3::from(*p))
    };
    (0..skeleton.bones.len())
        .map(|bone| {
            let head = position(bone);
            let tail = skeleton
                .parents
                .iter()
                .position(|p| *p == Some(bone))
                .map_or(head, position);
            m2m_core::geodesic::BoneSegment { head, tail }
        })
        .collect()
}

/// A rig's joints as a rest pose, plus each joint's parent within the joint list.
///
/// A joint's parent is its parent **node**, looked up in the joint list. That
/// is only correct while no rig puts a plain node in the middle of a bone
/// chain, and all nine shipped rigs satisfy it — measured: the direct-parent
/// rule and a full nearest-joint-ancestor walk agree on every joint of every
/// rig, and each has exactly one root. The walk was written first and removed
/// once the measurement showed it was untested defensive code;
/// `every_rig_hangs_its_bones_directly_off_each_other` is what fails if a
/// future asset breaks the assumption.
fn rest_pose(
    document: &m2m_io::glb::Document,
    name: &str,
) -> Result<(RestPose, Vec<Option<usize>>), RigError> {
    let skin = document
        .skins
        .first()
        .ok_or_else(|| RigError::NoSkin(name.to_owned()))?;
    let world = document.world_transforms();

    let mut joint_of = vec![None; document.nodes.len()];
    for (slot, &node) in skin.joints.iter().enumerate() {
        if let Some(entry) = joint_of.get_mut(node) {
            *entry = Some(slot);
        }
    }

    let parents = skin
        .joints
        .iter()
        .map(|&node| {
            let parent = document.nodes.get(node)?.parent?;
            joint_of.get(parent).copied().flatten()
        })
        .collect();

    let rest = RestPose {
        bones: skin
            .joints
            .iter()
            .filter_map(|&j| document.nodes.get(j).map(|n| n.name.clone()))
            .collect(),
        positions: skin
            .joints
            .iter()
            .filter_map(|&j| world.get(j).map(|m| m.transform_point3(glam::Vec3::ZERO)))
            .collect(),
    };
    Ok((rest, parents))
}

/// A document's geometry as one mesh in world space.
fn mesh_of(document: &m2m_io::glb::Document) -> m2m_core::mesh::Mesh {
    let world = document.world_transforms();
    let mut mesh = m2m_core::mesh::Mesh::default();
    for primitive in &document.primitives {
        let transform = primitive
            .node
            .and_then(|n| world.get(n).copied())
            .unwrap_or(glam::Mat4::IDENTITY);
        let base = mesh.positions.len() as u32;
        for chunk in primitive.positions.chunks_exact(3) {
            mesh.positions
                .push(transform.transform_point3(glam::Vec3::new(chunk[0], chunk[1], chunk[2])));
        }
        mesh.indices
            .extend(primitive.indices.iter().map(|i| i + base));
    }
    mesh
}

#[cfg(test)]
mod tests {
    use super::{fit, templates};

    fn model(relative: &str) -> Vec<u8> {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../legacy/static/").to_owned() + relative;
        std::fs::read(&path).unwrap_or_else(|e| panic!("reading {path}: {e}"))
    }

    #[test]
    fn every_shipped_template_has_the_rig_it_names() {
        // A manifest naming a `.glb` that is not embedded would fail only when
        // a user picked that creature, which is the worst time to find out.
        let offered = templates().expect("the shipped manifests parse");

        assert_eq!(offered.len(), 9);
        for template in &offered {
            assert!(template.available, "{} has no bundled rig", template.name);
            assert!(template.bones > 0, "{} claims no bones", template.name);
            assert!(
                !template.chains.is_empty(),
                "{} has no chains",
                template.name
            );
        }
        assert_eq!(offered.iter().map(|t| t.bones).sum::<usize>(), 500);
    }

    #[test]
    fn fitting_places_the_human_rig_on_a_human_mesh() {
        let fitted = fit("human", &model("models/model-human.glb")).expect("fits");

        assert_eq!(fitted.bones.len(), 66);
        assert_eq!(fitted.positions.len(), 66);
        assert_eq!(fitted.parents.len(), 66);
        assert!(fitted.bones.contains(&"pelvis".to_owned()));

        // The model is 1.83 m tall and the rig was authored at the same scale,
        // so a fit that had to scale by 10 would mean the units were wrong.
        assert!(
            (0.5..2.0).contains(&fitted.scale),
            "scale {} is not plausible",
            fitted.scale
        );
    }

    #[test]
    fn exactly_one_bone_is_a_root_and_every_other_parent_is_real() {
        // A skeleton is drawn as segments from each bone to its parent, so a
        // parent index that is out of range, or a second root, is a hole in
        // the drawing rather than an error anyone would see.
        let fitted = fit("human", &model("models/model-human.glb")).expect("fits");

        let roots = fitted.parents.iter().filter(|p| p.is_none()).count();
        assert_eq!(roots, 1, "expected one root, got {roots}");
        for (index, parent) in fitted.parents.iter().enumerate() {
            let Some(parent) = *parent else { continue };
            assert!(
                parent < fitted.bones.len(),
                "bone {index} has no such parent"
            );
            assert_ne!(parent, index, "bone {index} is its own parent");
        }
    }

    /// Every shipped rig hangs each bone directly off another bone.
    #[test]
    fn every_rig_hangs_its_bones_directly_off_each_other() {
        // What `rest_pose`'s parent lookup assumes. A rig with a plain node in
        // the middle of a chain would silently produce a second root and a
        // skeleton drawn with a hole in it, so the assumption is asserted
        // rather than trusted.
        for template in templates().expect("manifests parse") {
            let fitted = fit(&template.name, &model("models/model-human.glb"));
            // Fitting a human mesh with a shark rig is allowed to fail; the
            // parent structure is what is under test, so read it directly.
            let Ok(fitted) = fitted else { continue };
            assert_eq!(
                fitted.parents.iter().filter(|p| p.is_none()).count(),
                1,
                "{} does not have exactly one root",
                template.name
            );
        }
    }

    /// A bone points at its child, not back at its parent.
    #[test]
    fn a_bone_runs_from_its_own_joint_towards_its_child() {
        use super::{bone_segments, FittedSkeleton};

        // A three-bone chain at 0, 1 and 2 on Y.
        let skeleton = FittedSkeleton {
            bones: vec!["root".into(), "middle".into(), "tip".into()],
            parents: vec![None, Some(0), Some(1)],
            positions: vec![[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 2.0, 0.0]],
            scale: 1.0,
        };
        let segments = bone_segments(&skeleton);

        // Reversing the convention gives head 1 tail 0 here, which is why the
        // heads are asserted too and not only the tails.
        assert_eq!(segments[0].head, glam::Vec3::ZERO);
        assert_eq!(segments[0].tail, glam::Vec3::new(0.0, 1.0, 0.0));
        assert_eq!(segments[1].head, glam::Vec3::new(0.0, 1.0, 0.0));
        assert_eq!(segments[1].tail, glam::Vec3::new(0.0, 2.0, 0.0));
        // A leaf has no child, so its segment is a point rather than a
        // backwards line.
        assert_eq!(segments[2].head, segments[2].tail);
        assert_eq!(segments[2].head, glam::Vec3::new(0.0, 2.0, 0.0));
    }

    /// Binding attaches every vertex to something.
    #[test]
    fn binding_leaves_no_vertex_behind() {
        // `m2m_core::skinning`'s first invariant: an unweighted vertex detaches
        // when the rig moves. Measured on the reference body — 7,399 vertices,
        // none unweighted, none needing the straight-line fallback because the
        // mesh is one connected piece.
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let report = super::bind(
            &model("models/model-human.glb"),
            &skeleton,
            m2m_core::skinning::DEFAULT_FALLOFF,
        )
        .expect("binds");

        assert_eq!(report.vertices, 7399);
        assert_eq!(report.unweighted_vertices, 0);
        assert_eq!(report.fallback_vertices, 0);
        assert_eq!(
            report.influence_histogram.iter().sum::<usize>(),
            report.vertices,
            "every vertex is in exactly one bucket"
        );
        // Measured, and recorded because it is a large difference in character
        // from a hand-authored rig: the geodesic solver gives 96% of vertices
        // the full four influences, where the reference Mixamo export gives 93%
        // of its vertices exactly one. Whether that is too smooth is what the
        // legacy A/B in `memory/test.md` §9 is for.
        assert_eq!(report.influence_histogram, [254, 3, 38, 7104]);
    }

    /// The root and every leaf are kept out of the weighting.
    #[test]
    fn only_bones_between_the_root_and_the_leaves_hold_weight() {
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let report = super::bind(
            &model("models/model-human.glb"),
            &skeleton,
            m2m_core::skinning::DEFAULT_FALLOFF,
        )
        .expect("binds");

        // Recomputed from the skeleton rather than hardcoded, so this says what
        // the rule IS, not merely what it counted to on one rig.
        let has_child: Vec<bool> = (0..skeleton.bones.len())
            .map(|bone| skeleton.parents.contains(&Some(bone)))
            .collect();
        let expected = (0..skeleton.bones.len())
            .filter(|&b| skeleton.parents[b].is_some() && has_child[b])
            .count();

        assert_eq!(report.weighted_bones, expected);
        assert_eq!(
            report.weighted_bones + report.excluded_bones,
            skeleton.bones.len()
        );
        // One root and thirteen leaves on the human rig.
        assert_eq!(report.excluded_bones, 14);
    }

    /// A skeleton with nothing between root and leaf cannot hold weight.
    #[test]
    fn a_skeleton_with_no_weightable_bone_is_refused() {
        use super::FittedSkeleton;

        // Two bones: a root and its leaf. Neither may hold weight, so binding
        // has nothing to assign and must say so rather than assert its way out
        // of `assign_weights`, which panics on an empty mask.
        let skeleton = FittedSkeleton {
            bones: vec!["root".into(), "tip".into()],
            parents: vec![None, Some(0)],
            positions: vec![[0.0, 0.0, 0.0], [0.0, 1.0, 0.0]],
            scale: 1.0,
        };
        let err = super::bind(
            &model("models/model-human.glb"),
            &skeleton,
            m2m_core::skinning::DEFAULT_FALLOFF,
        )
        .expect_err("refused");

        assert!(
            matches!(err, super::RigError::NothingToBind { .. }),
            "got {err:?}"
        );
    }

    /// A cube of `size`, centred at `at`, as positions and triangle indices.
    fn cube(at: glam::Vec3, size: f32) -> (Vec<f32>, Vec<u32>) {
        let h = size / 2.0;
        let mut positions = Vec::with_capacity(24);
        for corner in 0..8 {
            let sign = |bit: u32| if corner & (1 << bit) == 0 { -h } else { h };
            positions.extend_from_slice(&[at.x + sign(0), at.y + sign(1), at.z + sign(2)]);
        }
        // Two triangles per face, wound consistently enough to voxelise.
        const FACES: [[u32; 4]; 6] = [
            [0, 1, 3, 2],
            [4, 6, 7, 5],
            [0, 4, 5, 1],
            [2, 3, 7, 6],
            [0, 2, 6, 4],
            [1, 5, 7, 3],
        ];
        let mut indices = Vec::with_capacity(36);
        for f in FACES {
            indices.extend_from_slice(&[f[0], f[1], f[2], f[0], f[2], f[3]]);
        }
        (positions, indices)
    }

    /// A `.glb` of two cubes, far enough apart to share no voxels.
    fn two_islands() -> Vec<u8> {
        let mut document = m2m_io::glb::Document {
            nodes: Vec::new(),
            primitives: Vec::new(),
            skins: Vec::new(),
            clips: Vec::new(),
            report: m2m_io::glb::GlbReport::default(),
        };
        document.nodes.push(m2m_io::glb::Node {
            name: "islands".into(),
            parent: None,
            transform: m2m_io::glb::Trs {
                translation: [0.0, 0.0, 0.0],
                rotation: [0.0, 0.0, 0.0, 1.0],
                scale: [1.0, 1.0, 1.0],
            },
            skin: None,
        });
        for (mesh, at) in [glam::Vec3::ZERO, glam::Vec3::new(10.0, 0.0, 0.0)]
            .into_iter()
            .enumerate()
        {
            let (positions, indices) = cube(at, 1.0);
            document.primitives.push(m2m_io::glb::Primitive {
                mesh,
                node: Some(0),
                positions,
                indices,
                joints: Vec::new(),
                weights: Vec::new(),
            });
        }
        m2m_io::glb::write(&document).expect("writes")
    }

    /// A model in two pieces gets its far piece attached, and says so.
    #[test]
    fn a_disconnected_island_is_attached_by_the_fallback_and_reported() {
        // The geodesic field spreads through the VOXEL GRID, not mesh
        // topology, so separate meshes that sit next to each other are still
        // reachable — measured: the nine-mesh reference character reports zero
        // fallbacks. Only geometry with real empty space around it, like a
        // prop modelled away from the body, takes this path.
        let skeleton = super::FittedSkeleton {
            bones: vec!["root".into(), "body".into(), "tip".into()],
            parents: vec![None, Some(0), Some(1)],
            positions: vec![[0.0, -0.4, 0.0], [0.0, 0.0, 0.0], [0.0, 0.4, 0.0]],
            scale: 1.0,
        };

        let report = super::bind(&two_islands(), &skeleton, 2.0).expect("binds");

        // The far cube's eight corners cannot be reached through the mesh.
        assert_eq!(report.fallback_vertices, 8, "{report:?}");
        // Attached all the same: a guessed bone beats detaching.
        assert_eq!(report.unweighted_vertices, 0);
        assert_eq!(
            report.influence_histogram.iter().sum::<usize>(),
            report.vertices
        );
    }

    /// The exported file is a rigged model any glTF reader can open.
    #[test]
    fn the_export_carries_the_mesh_the_skeleton_and_the_weights() {
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes =
            super::export_glb(&model("models/model-human.glb"), &skeleton, 2.0).expect("exports");

        // Written so the Blender and assimp checks have something to open.
        let path = std::env::temp_dir().join("m2m-export-check.glb");
        std::fs::write(&path, &bytes).expect("writes");
        println!("wrote {}", path.display());

        let back = m2m_io::glb::read(&bytes).expect("reads back");
        assert_eq!(back.skins.len(), 1);
        assert_eq!(back.skins[0].joints.len(), skeleton.bones.len());
        assert_eq!(
            back.skins[0].inverse_bind_matrices.len(),
            skeleton.bones.len(),
            "a joint without a bind matrix binds to the identity"
        );
        assert_eq!(back.nodes.len(), skeleton.bones.len() + 1);
        assert_eq!(back.primitives.len(), 1);

        // glTF puts the skin on the NODE, not the mesh. A file with an
        // armature and a mesh that references no skin imports unweighted —
        // `glb::Node`'s own docs warn about exactly this — and every count
        // above still looks right when the link is missing.
        let skinned: Vec<usize> = back
            .nodes
            .iter()
            .enumerate()
            .filter(|(_, node)| node.skin == Some(0))
            .map(|(index, _)| index)
            .collect();
        assert_eq!(skinned.len(), 1, "exactly one node must carry the skin");
        assert_eq!(
            back.primitives[0].node,
            Some(skinned[0]),
            "the primitive must hang off the node that carries the skin"
        );

        // Every vertex carries four influence slots, and they still sum to one
        // after the round trip through the file.
        let primitive = &back.primitives[0];
        let vertices = primitive.positions.len() / 3;
        assert_eq!(primitive.joints.len(), vertices * 4);
        for vertex in primitive.weights.chunks_exact(4) {
            let total: f32 = vertex.iter().sum();
            assert!((total - 1.0).abs() < 1e-3, "weights sum to {total}");
        }
    }

    /// The exported skeleton stands where the fitter put it.
    #[test]
    fn a_bones_world_position_survives_the_export() {
        // Bone nodes carry OFFSETS from their parent, so a version that wrote
        // world positions as local ones would look right in a flat scene and
        // pile every bone on top of the last in a deep chain.
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes =
            super::export_glb(&model("models/model-human.glb"), &skeleton, 2.0).expect("exports");
        let back = m2m_io::glb::read(&bytes).expect("reads back");
        let world = back.world_transforms();

        let mut worst = 0.0f32;
        for (bone, expected) in skeleton.positions.iter().enumerate() {
            let got = world[bone].transform_point3(glam::Vec3::ZERO);
            worst = worst.max(got.distance(glam::Vec3::from(*expected)));
        }
        assert!(worst < 1e-4, "worst bone moved {worst} m in the export");
    }

    /// The bind pose is the identity: the mesh does not move until a bone does.
    #[test]
    fn the_exported_mesh_sits_still_in_its_bind_pose() {
        // `jointWorld * IBM` must be the identity, or the model deforms the
        // instant it is opened — which no count of bones or vertices reveals.
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes =
            super::export_glb(&model("models/model-human.glb"), &skeleton, 2.0).expect("exports");
        let back = m2m_io::glb::read(&bytes).expect("reads back");
        let world = back.world_transforms();

        let mut worst = 0.0f32;
        for (slot, &joint) in back.skins[0].joints.iter().enumerate() {
            let ibm = glam::Mat4::from_cols_array(&back.skins[0].inverse_bind_matrices[slot]);
            let product = world[joint] * ibm;
            for (a, b) in product
                .to_cols_array()
                .iter()
                .zip(glam::Mat4::IDENTITY.to_cols_array().iter())
            {
                worst = worst.max((a - b).abs());
            }
        }
        assert!(worst < 1e-5, "bind pose is off by {worst}");
    }

    /// The FBX export carries the same rig, in the units it declares.
    #[test]
    fn the_fbx_export_declares_centimetres_and_uses_them() {
        // `fbx::build` writes UnitScaleFactor 1.0, which means centimetres.
        // Metre values in that file import as a 1.8 cm character, and no count
        // of bones or vertices would show it.
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes =
            super::export_fbx(&model("models/model-human.glb"), &skeleton, 2.0).expect("exports");

        let path = std::env::temp_dir().join("m2m-export-check.fbx");
        std::fs::write(&path, &bytes).expect("writes");
        println!("wrote {}", path.display());

        let scene = m2m_io::fbx::dom::Scene::from_document(
            m2m_io::fbx::binary::parse(&bytes).expect("our own reader reads it"),
        );
        assert_eq!(scene.unit_scale, Some(1.0), "the file declares centimetres");

        let models = m2m_io::fbx::model::parse_all(&scene);
        let bones: Vec<&m2m_io::fbx::model::Model> =
            models.models.iter().filter(|m| m.is_bone()).collect();
        assert_eq!(bones.len(), 66);

        // A human is 1.2 to 2.5 m, which in this file must read as 120 to 250.
        let ys: Vec<f64> = bones
            .iter()
            .map(|b| b.world.transform_point3(glam::DVec3::ZERO).y)
            .collect();
        let height = ys.iter().copied().fold(f64::MIN, f64::max)
            - ys.iter().copied().fold(f64::MAX, f64::min);
        assert!(
            (100.0..250.0).contains(&height),
            "skeleton spans {height} file units, which is not a character in centimetres"
        );

        // And the MESH, in the same units. Scaling the bones without the
        // geometry leaves a skeleton a hundred times the size of the body it
        // is meant to deform, and the skeleton assertion above still passes.
        let geometry = scene.objects_of_kind("Geometry");
        let mesh = m2m_io::fbx::geometry::parse(
            geometry.first().expect("a geometry"),
            m2m_io::fbx::geometry::GeometricTransform::default(),
        )
        .expect("parses");
        let mesh_ys: Vec<f32> = mesh.positions.chunks_exact(3).map(|p| p[1]).collect();
        let mesh_height = mesh_ys.iter().copied().fold(f32::MIN, f32::max)
            - mesh_ys.iter().copied().fold(f32::MAX, f32::min);
        assert!(
            (100.0..250.0).contains(&mesh_height),
            "mesh spans {mesh_height} file units against the skeleton's {height}"
        );
    }

    /// The bind pose the clusters record is the pose the skeleton is in.
    #[test]
    fn every_cluster_binds_to_where_its_bone_actually_is() {
        // FBX binds with a PAIR of global matrices, and `TransformLink` is the
        // bone's world at bind. Getting it wrong — the identity, say — leaves
        // every count correct and every vertex bound as though its bone sat at
        // the origin, so the mesh tears apart the moment it is posed. Neither
        // Blender's report nor assimp's would say a word.
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes =
            super::export_fbx(&model("models/model-human.glb"), &skeleton, 2.0).expect("exports");

        let scene = m2m_io::fbx::dom::Scene::from_document(
            m2m_io::fbx::binary::parse(&bytes).expect("reads"),
        );
        let models = m2m_io::fbx::model::parse_all(&scene);
        let (skins, _) = m2m_io::fbx::skin::parse_all(&scene);

        let mut worst = 0.0f64;
        for cluster in &skins[0].clusters {
            let bone = models.get(cluster.bone_id).expect("the cluster's bone");
            for (a, b) in bone
                .world
                .to_cols_array()
                .iter()
                .zip(cluster.transform_link.to_cols_array().iter())
            {
                worst = worst.max((a - b).abs());
            }
        }
        assert!(
            worst < 1e-6,
            "a cluster binds {worst} away from where its bone stands"
        );
        assert!(!skins[0].clusters.is_empty());
    }

    /// Every solved influence reaches a cluster, and no bone gets an empty one.
    #[test]
    fn the_fbx_clusters_carry_every_influence_exactly_once() {
        let skeleton = fit("human", &model("models/model-human.glb")).expect("fits");
        let bytes =
            super::export_fbx(&model("models/model-human.glb"), &skeleton, 2.0).expect("exports");

        let scene = m2m_io::fbx::dom::Scene::from_document(
            m2m_io::fbx::binary::parse(&bytes).expect("reads"),
        );
        let (skins, _) = m2m_io::fbx::skin::parse_all(&scene);
        assert_eq!(skins.len(), 1);

        // The report and the file are computed by different code from the same
        // solve, so agreeing is worth something.
        let report = super::bind(&model("models/model-human.glb"), &skeleton, 2.0).expect("binds");
        let influences: usize = skins[0].clusters.iter().map(|c| c.indices.len()).sum();
        let expected: usize = report
            .influence_histogram
            .iter()
            .enumerate()
            .map(|(slot, count)| (slot + 1) * count)
            .sum();
        assert_eq!(
            influences, expected,
            "an influence was dropped or duplicated"
        );

        // A bone that influences nothing gets no cluster, not an empty one.
        assert!(skins[0].clusters.iter().all(|c| !c.indices.is_empty()));
        assert!(skins[0].clusters.len() <= report.weighted_bones);

        // Every weight is a real share, and the parallel arrays line up.
        for cluster in &skins[0].clusters {
            assert_eq!(cluster.indices.len(), cluster.weights.len());
            assert!(cluster.weights.iter().all(|w| *w > 0.0 && *w <= 1.0));
        }
    }

    /// A skeleton whose parent comes after its child is refused, not panicked on.
    #[test]
    fn a_bone_ordered_after_its_parent_is_refused() {
        // `fbx::build` panics on this rather than returning an error, and a
        // FittedSkeleton comes in from the frontend.
        let skeleton = super::FittedSkeleton {
            bones: vec!["child".into(), "parent".into()],
            parents: vec![Some(1), None],
            positions: vec![[0.0, 1.0, 0.0], [0.0, 0.0, 0.0]],
            scale: 1.0,
        };
        let err = super::export_fbx(&model("models/model-human.glb"), &skeleton, 2.0)
            .expect_err("refused");

        assert!(
            matches!(err, super::RigError::BadBoneOrder { bone: 0, parent: 1 }),
            "got {err:?}"
        );
    }

    #[test]
    fn a_template_nobody_ships_is_refused_by_name() {
        let err = fit("chimera", &model("models/model-human.glb")).expect_err("refused");
        assert!(
            matches!(err, super::RigError::UnknownTemplate(name) if name == "chimera"),
            "wrong error"
        );
    }

    #[test]
    fn a_file_that_is_not_a_model_is_refused_rather_than_fitted() {
        let err = fit("human", b"\x89PNG\r\n\x1a\n not a model").expect_err("refused");
        assert!(matches!(err, super::RigError::Import(_)), "got {err:?}");
    }
}
